apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: tracearr
    namespace: tracearr
spec:
    interval: 15m
    chart:
        spec:
            chart: tracearr
            version: 1.0.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: tracearr
    values:
        global:
            stopAll: false
        ingress:
            main:
                enabled: true
                ingressClassName: internal
                hosts:
                    - host: tracearr.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix