apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:JfS22g54Icgo3VEVCZU8v4rwTHGK2ckTE3jewVpmyk1vbxK5UPX60xEt0W3Ho8uvZNuQUUJMcooJYYqedMsaDvrAjpAeHODfoNPnXIoR4NXRJwPLrc/9P9NSuZA7YHZvFYdw9wAMwR8Qrme4fCWm8Z+HkJ/wlAcnd+GW1+2Emv/Mp5BY3unW1st/Yv9kreaLvjXErotNNPs3TF6woarJUDL2sX8/ysVM6TOa6qL/uW+bj59icilLgNb6AXCnZZ7UTsLsmpHZOa27nL9SmAl1FBRkOjOh8mk8oLODxgEsKORGix//QwAtZ2Ii+QYZPsERb8d278e87F5EWGkuM1OzTG6o7Vj9uzTxSlg3i/NEA+cIGSdKi6s+O0jjk6A8g819,iv:ZdE6pTw7VZMp54AUZxr5vCjIwdYzsypYG4DzXQitdTc=,tag:HGhSMD/Lm00l7jiDc2SX8w==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZXcJw7NYZyR8B6bwcfHoIyk/cQjJcoFgbPbVZXBOnd8sClcdZc6xF3Smj1tVNmJgJa+mkc1L+5gcJv2ggjUjwXhCB+8Xi0oB4Pzws9ZGj3yvLhKYb4di0vfriV1K8w0warPhpffJBDmKSq6yjEgpYDKJi9XZIphprGX8k5KuRxWa2XJrQK8d9wKznB6Ci815/CWff48Uiv3mc7xh1+InejAhjO6OAwyz648WiWWCi+tWnba9niNHZHSX77pGb+1jfulUDn5PaUvn4sngQw==,iv:R4+uQpLu+UrM17Q032BS11knykEyH1rr6JzZU45MaoU=,tag:jBtUtmAI3UfE3r74GagNew==,type:str]
    known_hosts: ENC[AES256_GCM,data:H5BRV1fvQlLBG8mDXfx86zzTRxfHP1itwVmZdgZOQ9za2GWf2ZCF1uHvqjziHXKa1vJjfTyH0uugZPK/qmPfMIPlzyu1B9wk1H92RlG5YTiZYmgsobsm49OSs77UhRh8qTstNRgwt4LOyYJpXtVkDhzaUaujCNk6b70etzejHe4lcvQI+cJMbdB35F+sqhjLABcb3yynTW7Vegg/DAkkqTJWFLZX/44katiS,iv:pPM8cC7IPi1QzrS3245nyWDBSZznWT0nVIa1VL0C2IE=,tag:xiwDsJJbyTkkeQDUZG/Y5w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUFNkOWM2MXlzVDNkRzZW
            cVFpS3VKem9hSVFyeUJWOXNXdG9FUExuYlc4CnZNcU9pZWE5TWxTWkF3MXF3VGJK
            UXZqaVJRb1JGUzNhMzB2a3BsQmZwOEUKLS0tIEFMVGxna3RKMEdBejFSYVc2UTJq
            RmhqS1VvUkd1Wll2WmxodFdDanV6OWcK3k4ZBAlOJihuqGR5A65JrSIK0e5y0isU
            IqHni8gBy4zzfczE0JvDzEW0FWoUsetowfPdXyuO3rmzV7QYh0lMcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T16:24:09Z"
    mac: ENC[AES256_GCM,data:PiCz+LtoJraNspYq0whbwiAuiV2NuGHGBryptVZdLs8STm33GgnpVEqXan3Vdo9XjKcnC7mH3xPK6Zn1mVPUja5l9SXG2iN4vhKUrFWCDWPYe2+9Bh6IxpC4z/pJA3NUZy8TtLaAxs2TJP/re+bB7m22HqM9ClJGCmrSa+kEHvA=,iv:rk4EKSfWWHw+0z9DRgZP69RgudRrUQn7BCpyItoQ1mw=,tag:7m96png3wr0bRrexsVg+pw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
