apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:a9YHFXLGdtZsW6yMH5HWQo+IzyQsXuh5WBRwaczSM0XUZ3y5MVsiLpybiba9s+7KKm4pflueDuGI71ODXTLrKAmIz7J9eHo3OTORtTDBq12llffCweqdsSU9++VglNagu+S86C4VON6vLdY4tZ7NhAga0TkFe3JVQDkQknRMMQqCioCzVnDnpAKsd8Utsonme6fn8zHNyfzaIRYNdO6HdJX7JZwCbRoajrzxx/SjMpA8iC8UGPKvEFx3HeRnRJYJMj40DXhwn2va71kNSa8fmAHYZ1iHb9xEJ3VdzaaoNsF0sV5jztYSolrNAuPFKq1ulpS+VgtP6jEuUMiFLc4/K+rEPT7U25txSOmi+CIsg0nEu4Cw5pH4yEQEbbJX4bwP,iv:jcf/o8QTA6gXWXwd2GQu2jCjxs6nhRTOl2IU3mJhloE=,tag:2Tx5tfZ182fjqnvFYA18kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:VVThKoWxJg6gGuXKMjtCqPFBZR/DenyP8kbkVqQl/s3HUh07GAJENFuZ1TdBoPiME0jG0Kc2qmsPyqJvjBqqNXKYCUBdZFddOA9mZ5o9fNJmO/yV2ooaQReY5Uv2Hkb9ps3OoPew86hYBDDPtz6gKHBFW+T0wZGpN1xaj6Ki/EIAOOVzCC22Dy87Z8I9erDypaubtkGg0jtI+ZoudHP8SklbhqZCOssZhCvCW6t9DG3UPPqQfk3lvGROp8v11SXEDZsgBIoUGgwZbgD5fg==,iv:a8q5VM3qhmPeX4MUB710xeeLvGWddzSU8ssuZY7KUmo=,tag:u44fQSyrW9IZ2NIIZUbU2A==,type:str]
    known_hosts: ENC[AES256_GCM,data:917q57xnPM0ybUzl+odLF6DRMGjaL0RT5yBUWme1XvvrmeLqUjQEdXelI/NUQ1J2EtSY7UYPZeOpTiC51VrfkClz7bG18LVBmDhYC66iJxDnOQXw8ym32wSjBjA0ENz61DQndQTuCnQPwwwr0co8l8arBC6LNvrjJOK9uOR2cE7PQryAZjkPWwhPIJNPHog1JGXgwMMs1hmPBHsI8WoYR7v/UAtCU8g0RNkI,iv:PZIQXGwBSF47r+lajjb9RLqhOkpER0HBZj8rpq8kCo8=,tag:gVgiKx6vgo7klogQv+oo8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4R0tFN3hESkZKV0VXYUw0
            a3plME1zaEJJWkVJdnRZTm96RVNMTWhmTDM0CmQ3Z0M2c0FCZEY4ZzlBNUJPY1lE
            a2Vnc3RKVzI1REE0WFpoZkdoMGtMaFkKLS0tIHpRSFQ1N1Q5dkYzaUhjQkdGMHZz
            WnplTi9rUVIyWWVYaS8zQ0h2bGVYUE0KLWBmDTzbYZGHE57SWtYmQNFe8F0Cs0EK
            1rQCdsNC2mfAFjIrN6WOwjsvpSSFdDuMUPgK//CCf6M78XuqhXpg1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T20:42:31Z"
    mac: ENC[AES256_GCM,data:2QaJMu/nbTIImV/suNlxLCwMbjItUX1Pc+Plk3lBvuv+fD2hNslGwI8i3Oz43+gTwcOKqfVhATITh4OnTm5Joyhh9DLPgCu+RtwHfPgjEJlnOrE3NDwXAWKu4db8pz2M7DRsCDhg8ESnQCXB6/xdb4sO7oimDM2RMvQsjh7mmhg=,iv:Hm1j7h8Kd9e+EbSW8ac6OfXuLyP8Xs/hLBKo5yEL5h8=,tag:LLc459fWEuBmimRnmENvUw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
