apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NJe0Egyf8sUekGxWptEMig4gp/dnaPBpd1lMJe3KTLZLqkJYapI5rgtznj2kG44F5A709YNXOjancBqLTtz7t/FLrTUwLkW6mzusFyyS3/bDg5aYyZx1a7ymaVB5G9b/rtkQ/TJV+ojElbs8EuFh59fqsH+rNf+bsNZNnILA4ySOU778B0evDKelBpo1PQP2kkO6tQIgjThsjCt/mCx5VgHqHvSumTHVuqr+gd3kLkqY4jH1qQcG8aoADeNvdW0DLtcJ8QYHwmIR+3oWFF403bl4qeBk4j6OZ9CA5yt1l2gWIQLQt/QVgjLNE+vD2n54JQ+e8n99nV/oysB//bN212sC0qIFxRwU4A7dq/ua6pQDMLANM7Zo/NJ3agPXBEoh,iv:Hf5etLODNx34isyMTDmw4+6Yy+QceIdojnwTUmk9Crw=,tag:Jdi8DHRC9okn6QCeGOmAyw==,type:str]
    identity.pub: ENC[AES256_GCM,data:YovAoSUiHdUgQbl7e4wZ1nAP6BMzaZM8SUpgyvN3WN5LCo8OakzBmTYPXYESrX7zInthA/HR4vB7xxYdR34sJsMGrxv9M9s0HT+7XqwB0B+D1auY0aaB/flHrVcI11L+0jJRT3Z/b/hDtFHbPbyUXorCd0hv/vxjhpYzKxkGYA1mQsrtHDGpS1TmyMdfPiBr3ya6WVDlXluP2jdiu454E1ZTqlcHbbp0SnhcPLuOspz1ypn9stWtEKz2gdm72zn1Biq2dE0YLYPreAM2lg==,iv:TERyBIeS3pxLsZvqilH8jLW1596lwfOpyd8HfYGd764=,tag:ECcnBmA6moErTwewRcsd8Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:CSJA5mCijEpnawO2iim8d0ow/Ge11+AB86qZ5rrCQ8e+keLT/RbdqR6o/ohY0k2i9bVDoTFyStNT5TduJlFKqIeaQNQ+T5wli5klUqM1Oe+MjX2iypwlvZhH8fTnfeoZNkZ75pMsfg5+37rOu+KIM4N1zH8URwKF7F2TkyVHPtLEiGLd7vBtIb4kqohikH2y7wqgOacpuXii3NEf0Ok/jRdl0cHK8jJGNWqt,iv:Mera6bFtMnP+n9uNkUJYjEsVi5pd9994gTVyguSqnN4=,tag:z7bWLtwzNVWUXytqPImUMg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb0NOOVFDbWM4bFU4K1cy
            L1ZNT3V0T1dDRmRnSk8wd21HMzhndVdXMWdNClZPVHJqSDVETWQvT0pBdWlLZUN0
            M2JzM3dZWTJrRitUbjZEQi91TUVmOGMKLS0tIFpjMC9MQ1JMYWpIYWdzMUZrblZh
            U1RjamZFSVdlUGVhVjIydWRTMzYxUWsK/2QgdFWvf0lnKDVs4lfWC+aT19uyPBd/
            D8bfE1mgqXPu1R3FRQN2dw90iBnYUl1zJbRAGM2ybGQdKC63c4QNlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:44:45Z"
    mac: ENC[AES256_GCM,data:4x3mMJF8brqQlvCObkP7rO9b54fqH1pmXZIoYUrEZ6Q3spGajXrXJNTGqdUIgkOsmQipupi5yNLqn1PjEClohqk1ZxhSQFhbYUOBJ+6dHpTAYxeW1tL8G48Fbe7MpBIyhJon/Ha2OzXnqrQeuPFuSP0iziinsaJ8q1J4bbl/IWA=,iv:ZJdwfJ1HCqc8r/QWXshe1bt0Z3nxwliVv4pRBrur7Hg=,tag:xjQsosyAtlriOZBfzjarQQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
