apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3GHBqGZV827vPrpf3xaYHqNAnlGc0lA1UmaHuiCD+AmlaXHJrTfQdkM+i2pT7Xx1TWyy5EHIWn5JxoG6cYhiPDLTnTB8qGPvf2kR5M2426VGrQrwn2odjSyYghp775+Vrla7foqu4mA1uQJSgfq33woUt/dMpERvQOm6gxcyn+kJ+WfUdFLnUBTJQdG1yJWWRbq5ceTsRoTqzdCoB89Z77GBKhtDX6MkLRfS7KRkuCPcEFs5jjr0w7mZ4KIY0VB6ldlcDmMRIPA3ZKzc5qGd6rojLpaRLcIKpnPT8nurxSIFaErsE4lHYG5HeMlrZqSaJYhpwIHVExcsMuuZ9UUD0qL1I2+f6u3YttlP881AdZvSue9t/Rql+vu04agaev82,iv:1J+gfHOIyJer6V+Kb0u4pcZXhtZ5YERczQfLfBuD0nU=,tag:qL+fzWmT9rqHsXPc6VZ7FA==,type:str]
    identity.pub: ENC[AES256_GCM,data:j1nF87PaWV2Zd4AXeWA1P5euWzeljeoIYiImYyY5L23x8+sZxHr9dDVSLCN5rr2YI5RVXeuaUj0RfcMHUV1XvEatnHk/I1LuO6kllpEqksG1sSMMrZsfaY9Wsqm+SiA/F0mccoH7xSR7HdAGOwS60AyCoNJwY+klbWPMggTw2M1aD7oiJcF3G9UsiJvI2iVOWtZWTBmsDUa9P10OJcqymn8vHV+osZkPrPgyDt19iHkjAAF7xku60uCQSMLrb9a+ZcT2JlV6lR+fKh+ZgA==,iv:vgmOvGvADQIF6BWRkpfwfHAOZokeDnhSY11/gEF57PM=,tag:1DxCPHz4BmPiYMTXmIsgkw==,type:str]
    known_hosts: ENC[AES256_GCM,data:362bUJvlf30f6zzBND9ljH89CfADC+Z6xUF3WwAH2xXoGcTRf+FBpoi6VoH//M/VWXow1M2/+MdzCdaxwmNPkwwyI8z7twubTpPZrp8fSglFzXaOVJoBRKPVRfWmrHvZ7VEiO/nqDLCmS3FbEpWiuZOfcGyKNa9NzDetBz1E7h2cse/a7FgrCEw4x0E2jhAR6zY9ze9h/RVWdqTULNvW0f4HNGPx7d6qGyIx,iv:8IlpKCWICjoHgFFeD+3lTWRMttCojYK/wll188sU5hw=,tag:CNDO8nIgjE256kWa6a7e1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRVZKRjRzS1V6aDFmOFNv
            dHpMME41c1lLc2tISWN5YlN3UEwxWE5OVVRVCnpXSEt3eHd6OGVJQ1E4KzFzMFY1
            bksxUnA1VVQ5QUJiVGhTUmJDMnQ4d1EKLS0tIDhGMEdtdGhnSFF6UjRzNDk3cDJx
            OHIzQWpGT2ViRTc2ZUh4TlZPZy96akUKfCWAhZ0M29oMYvOg3MddIL3+XZDIXm1b
            k60OGYfKn8GJ+ZxOYfJsYc2+BWmi7TxDslxhQ7DH3h+9UPWxXG6W6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T10:20:53Z"
    mac: ENC[AES256_GCM,data:6P1weyXBketJk7wznytmVSOxsrvJgmg5jAmBV3jX3kCfV/OUNKZL+Za5NQ6v04FWUAD4xppIRR7cnK5b5riC9WHOvFdR1tjQ+6u5J1zADFDpmYbEyCcardKOcRMtGPlss3SoXfi1C6sgjHsMcItEEdSzKrPeu5Z66vCP4bLBsrA=,iv:9a+uNNjwOdIMMxJxy8iVfkig9V7t6CtbmTJC+YKwPuo=,tag:rGXxJn/k4m6GWg1DSHO42w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
