apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nT87zHJbzIMhOID+6155bxAAHYsJ3CgK81JN5FDDk94bElxdSKgGJ+PZyGFz04pqNdTOfKjW28q9KOryX+7P4UZYpCVKsASvhO9ldan1bfvGy9igYDw9pVHx16NohA6RaWW+QzbFT0tZvs/znxlo1n11pEeJWiE1ki3tpXn/HG742+VBQYSsqa8WlLXdylV/dUO0BBH9XGU7zeJvj5rIEX/ajOyLqsoOw+TH9bk/WJ3rvXLak9lmyKZclQS4XGlbqeNw78HT1uNByhnuyMUTafXTekTioY+a8FtDEKSn6CAaENj9b39QMdhbaxOMSHWJaHwGTwko7gzVBI53TLDw/ucJt/HUdgP1ihynhGiMXZ2Jy0MLkqjwgpyWnRSK37nZ,iv:KzC2I5wgnfLUyer1umG3v1gAkXEQa5Zi7k/6xgzq2mk=,tag:6ypHu0/b8hQ59bKQlqXQ2g==,type:str]
    identity.pub: ENC[AES256_GCM,data:5iTpn6hvJXg6ObkUldW5bPeOTAUH44WnSsGJo7u++Qx/n3IvkxyfxLGPaXlAnemQAcTIwpr+EAe16aFThOkUchW9Dp2sk+gSiAFjK7GIqKXnChJzWNGY9fZuJqV0mGFNNiR+EnMetcgqDuQHCCq6iv08a150F8Wh0jZtirEvIc4vqGs6kQ5GTUq0RwVA1V2BPKB+SRqSl+fzLvu4JPMC+6fOtwCIeAoo4/uFX298OkGqXbwKaNiwI2E7ymAltDb3Fr0fA+ISPZM6PAmCzg==,iv:LSrGC4uPu72TRb06EaeIXaCQ3nhHGsGPc6RKVOgt2Ho=,tag:ucotgi95HGb1UfSeHgJ3Cg==,type:str]
    known_hosts: ENC[AES256_GCM,data:D6u7ltiEQhn1n8fSUoHSXFMKGQMK6zQFXURFpop/PnRWvwYcItxiyE1WDtz4budjC/bbvUqztPnYQOT9fhz0QQ2KE0//Egb2MNNXp1yXkN7zuLKRvufYiOV2Cu+hrBIorml46ojvmdzCfa/P23qY4VJrGUSyvJFEWvNqGWwja3mowMNn0ofzm3RXfh/kcU7yf8i5+Jr5WfIWfMHxa6sTIIcCgbniaGzyk+w5,iv:e+uHLrE11yFRwxvsH5t9aU8FWQTQK46ASsxwy78HjwI=,tag:siKGpM3rLROvs07Bf4yU4A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVmtxcUEzSnVvOW1wZ2t1
            WTk5TStiQVlLNnlHcjRmczA2VmpTOWVOWG5rCktKaU50VjJuaU1lT3lQQlh0dVQv
            MGRuNVZHbTYrN3RjbHFQNVZVbHovcUUKLS0tIHNFRmJSZVgrQnpPaUtPNDUzbS9M
            ZG5CQnJNUU5jNXI4TVliRnJaSmtHa2sK+Y/s8nsbtengq2DqNGiCVwnRo3usz6Jt
            Tz/AUAGJa1Lh2Me5NHVeT2quW8UcOUJOaiVQN8pnXWN7fH3paNhh6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T08:06:00Z"
    mac: ENC[AES256_GCM,data:5NKu19UDAZAax4Kb6lVVC+TtJpadu6BmUVz3Udq6lhl8fcisG5FtcBE0EO+NAzlD0SEbuDyCnCpeug3dRc6T6u2FOlnFFwBKS6+eRWNLFWMV8HG6hKHSSGbWNfKcEuq0qCNQYUxCLrTcpQPXyhGz8/idVAK+7gEkcWK+IhSodEk=,iv:RAedzuUv6wPuvPWfgW44b1vaqIw/kMiOAu5G9exI/gw=,tag:Q5gJmbJDHnVJkjSrDxpSEQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
