apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hyMh36WIyP/xGcUmPMp0/FXrqbe9esAaaxGdZPtblluwfEAMw9ipZAoYXn2rfgbVJUr5dKHYDNhcUQNbEqH+AvqLlF2ifKVdpKuqARC4uYQ/oUi0Kv+WUGk/U6M7SUqkSEJLRI36DVfvQI6I1BITbgwY3zL0zJyD4HGicqjujmb40eF0O8CiMUPV1bmOYv1cp4UTdDQhvpfVC7Nk6vqM9Zn7DrdgPEscQcO6DtuB99ucKUrPLQsa1sn+Ufc2BQsL5it+rHk+OVYWXsl1nT/j8XSd1oPoDNDKUo7VltR5C8zSwWwbjhJvnDEAlIw29u1zebvxrms84TGRFP/KPdkVEFicbkbnHoOTu/8wPlLRgmNv3yIu7xn4wMEJ5W0PC/Sf,iv:I7gV3qbwCAL6e3AVMNpKK06NKorb/0t6cNlUaxtImo0=,tag:WSvwD/abHhj7QyS8otAuDA==,type:str]
    identity.pub: ENC[AES256_GCM,data:WPFj9LWuvyz6NE4BidCfP/axX1loMmDbaAopAIoWtwWPzwp2JR/4HwUOmrzOXBwxkY3A2b49YPmZOfJU94orgWRMhlpWxf34uXDWjtk9wMsBAHl5aLmQ4u6U41mH1lRUKl6bS1CWC0wnfw+QNxNEXZ8vc95uE/lIxVxmobr7Dxj95EMBjDtg4Sm9WBBOmxKVTbpZC+y14WsAGbfWhMGt+syAzW4lyODQVxOWbstrP7/7+h8Gqw813hoDzEIagGmN8Nj0G92NY6VE0iNcdQ==,iv:I5Os3cJUzyPbnWo+81h9X/5i2oGhYbpZIohPc+7YKBE=,tag:bQh92Yyb90Wb4tQOmYhG7A==,type:str]
    known_hosts: ENC[AES256_GCM,data:KX5tN4p3C3BPkmTq6KjKf/Jf220jtkvPB6Hn91XqqW2VZ1lX+mNWCpZdHJlE/+/CnlgGFbGZ2r0N7TshZUs4iFxK4dpso9DN/0QXc5A5E7rc5+AkK6TPtGE2mSsIZZ9/iXgJxmbL1kilBJOWO3cgmkD9TsNGz28wxy2DWYN85H7PGzWKfti0BTFes4Ls254mSdfsE5DjYIPKsMHstJFF3y45teihmoviHUi1,iv:GSycKue6BTdr+TiwwpapmGOZi/pLBK07VTwatQ7wHYY=,tag:YogpQZnbOceA1o6O+y0ogg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNEFNUHZoWmo1WVdVb1Fk
            NHI1V3JibnBtRFEzeFJJTmVvVUJOZFB0ZXlZCmZmMkxTVG9YdXlaNTZhL3RJbFhC
            bkxURXpwMnhLMklzcjNaYUFPVUdDYkkKLS0tIHVwZU9sUlNyMUZhcXQ3RVptczFQ
            dDBJdlZoUUNub2FQR2p2Qmgyb3dJZm8Kk/y+DGvjPJs9HMFNnxU84+9QDAcii9Ex
            Lpjb0NJvRP+3BPqjeMFKbWcKLbQM57aWGoJSDPm4nmufoFTVAjfjfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:57:07Z"
    mac: ENC[AES256_GCM,data:TwjsTm6w7IejSR6h1klACYIcCVRYf9GoY2Z94iG3jJL1At3fGOs2XohSoHxyXmCSvTmEpDaS6duNt+1cGh51JOWnA6Q6TQ9W8HrKFgFJ9WixSzkvJa27XdqXrKT2bXk82/Q9p8DKEEyLB4hI9aZL7pXgSR8vxlLJ8NVBg0KgStQ=,iv:jtZyazJA4+b5m0AjEbjznGDYnZJMnkflAFL20F8DPso=,tag:yGWFaoNTBLYZExaIfUg0yQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
