apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:HtiRWcwr4cnFXAOW/kz4GmGHwfqyuBfLyfBMQQ+LFwGl4iPCCOE+Bp89FfBH3ApE1Lm+N6qvlrMZKMXDn5o+GA2GovfgW+4m5INodNTp7/yz0m21FAS0hbAzeNHfKzMcFmAIremwwT3pXZjabEFCzxjm64i2Nmncs71NujVSypYwY6h5h2HdbydS4ok5sEF4f/BKIzZ87bxUeN5HTb+khaEk5Rj2Q3WsMtpxnDmiC5o20ZrwON20MQ2LGH5scAGRkIVNBYY12nH4X534CGSMTDXXVKv+d9rgzOqen33IVaPcLVwsqB2nar5r7BGoc/cQDRHHFkWZCWcOFt5huyQO7W+xjVsSUMFZ3ZfCfoFbdU66zcPPn5gFPPas/oRbwJkC,iv:2txzQjrEStzvPbG+Gr2/zorOlLbpjLrAj5uCajKfmmw=,tag:oRb/lcLApXO7a0vR+N2jvA==,type:str]
    identity.pub: ENC[AES256_GCM,data:37FYA/KQfb5lWIHhQFuHKqp5lsyyDR6roYhYYfu945mr8ZNJDiDOIKXltCOzsi62rDhaYGRP0e2JEAFD2lcSBdamVvVekGvbDPgYnH323S/u33kZ0mNeAThoqrx4NStMrRVLeETCMBEKR4kOMrte0tNobB3OMPE+xrhZcfacY+v+QfxTG3HEeK0dGWkEN4/d21f3L8dlrS2FipKSIGHefG4owg8b4FmPnTWf9PN3FOAk6RMKNe48waR9yTwN+AbgQvysXxSaeqfVG2hL0A==,iv:GSjBEokrt5HgYASgI740jlgwGBgRjRnCzsdzVTdiG2k=,tag:3Q6M48/3/mYn3aOL2Zyjng==,type:str]
    known_hosts: ENC[AES256_GCM,data:GTRkLml7XoVVknA4EPmrEEUCUwlCaZQCFqYrbAcslG5DPqJx8wmtnx4hS2RgTjMjpnqmN/ADhl5x6S1Kgrrhn52QdCsMjVLzgrUBwsGD9FfR94EvhEUVZCZl65rty8V8Kj335Lz6Ag81EKkSrDN20S0zUIBEqlYhP4w1ScEeqPDpLM5IXjKRT8/5Li0ARirF2tkKmsJC4VdFhgonCkpvoQ7sWoOihVcPY4ab,iv:OWMUKaKHdCjTLcsD0mKPTVmR1yTw1sH1R7BT9w8d9AA=,tag:mSuQcGdvIhDmD3CL9FmkWA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN1ZjdzJCU0E4dHVTN3lY
            QWlqSDI1MkN4cDBYM0dlTThtUlVOcGxYeG1vCkNsVGRFVldsbFZXTTB6c3A3US8w
            NmF0V2gvT1NRaTZYa1dSbHNxOFNjcUEKLS0tIFN3bUphRmVFV2xXRUtyY3RtOFB3
            K1BCbmRNRmloZ0UycHZPUG9lcnR5RjQKe7dkciea5+12rrAQGfSCqC0cKgDiqVJv
            SimfSSVwe+8CKYrAp0bhxa+pOdM/E9d1u9UWRItlXJ8qlAURI3Dc4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T10:13:22Z"
    mac: ENC[AES256_GCM,data:q1cMz/oZOItSX5+w9GZVJXFurqSQz3zWCA+AUhOI9x8eQI3eAaDyMS9m6X6ylerDpB3lPbkBdoZtkzvJhirf8NnxfBiFH6qMfyR9Hj77DF2pmNztXLGr565Onys0Ioq5gAL3CoiICnzL9MtzUTeSi+JraZkXm8ZikP0iUTiskSk=,iv:3+6lc45JtR2Kq57TxfDTplh4ffQpvpGVKqCQjpqkwh8=,tag:cNLq/yiTJtbrDU8SNyhOuw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
