apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:yObLemj18IVGfG5E4tyXSQJsoXcd9UrTx3+TD3ABkjZlqebQhqdlJMBnyR3tzQiy3fzf8w6gpkEBfnkvNBzD7apKHi+WJnENhUrSiCpDvcVNIGxw9ksMI6ep9uQB0uXG1sKXROXxwQewunx7nIhCdPFpD7nei5KVDr7TyWONKCs5DoTUIul6ndTVhSMdYVbdodc5ML0yjAcdF680+pvlDMDpVOjSOPko2hBIrh97Uhs1BD/S+sSVMiOmCMvqUkD30AIhfki5Bn7ACY5zCVyy794KLrGPh+UTwQWtVgaSfbV8eovaT67yVZcTLQGFR2xzPDgmKbH/GNQg23bHxzhBB6+B4wDqbFBe5RIIgvBxDIKZVAl1I/nBATC9aPrpNAWb,iv:5Qo5N+ujxxru6iR4/aVvqvibHnUDZyCmAw/PJFss8IQ=,tag:/zCSXmQ+ZXYdMnfxpqHM/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:T1tr6kDUDQ43+2hZ54QdSctUof+DSctGpRD9nVC4V2GjSf/CR6xiKqoYkHDt3Bi7TPOXs3BCq3OTfwDTrfB8mKeXK2sCnJ0gS0cE1pYyC1LFp/Stzf1PmS7kovNJGOfUNbLY8bXkaDp5ZksDo9ge20Bv5yLlQC/+CTBPN2PbqAeQW4BMwHS9Jdamsg7XwetYVzDi9l6u3bFOdnYBhIX9/XSuT18OEfrAT88BmXnGMQbQvTHe4URfR5uEkPAgnJSRb8AsWfJxFGX+XsO08w==,iv:IOhK3joHMfZbXM/r2RQeShGNVit1FoHTTBTLvXUY3M4=,tag:cC/BCkcOLYkXCAGoXatmDg==,type:str]
    known_hosts: ENC[AES256_GCM,data:oB2CxSKfn6WoyLRJoPzHsDQ00LtoQ2b+qwpR4vy/aBHkv3X0wTLqT1qw1BzIEwJlMmsSiCymwYlC674XmmZ96c5xKVDLywIJ0rfRZLp4unkkf84dYnVHfh4GWiOKKF2WIg4wGxUKriVRaNNrliO8hXVp4XZxRnj2SjRXlTM9fKBBkZnAP/9ZFrMVHWYwc2OePwltWbYEdWsR0V+9dE1eMX0O9qX4GoQsnJLz,iv:p/Mv0ge+hnM5Hy4pBrt4dSo9V9/zVwYX3FzO9uXUq5k=,tag:lMUC/MQ6miwfwgIL5kuvkA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHd25mbTVHNEdSY2hxb3Jn
            R1JKeXE4aXJmaEtFS3FjMmxoZlFOWmEwNUZJCkNyTUd4SkcxUGRiS2VkYysrRGJO
            azQySFBlSDAyT0o3WGpQMmF0YUFyd00KLS0tIE5KTG5kbldRQll5cGhOUGM4eEs3
            VTNHdnpOZ2RWTzV0RWtYQ2hSZU8wUWMKXuUPClabgYvt6RHeoJ6jpgzwjxo4f8hl
            b4U9rquoJmi2hH3y7M5JWwd3BYThXimmNqHvK8oUhVq9rMNmWAUj0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T07:53:06Z"
    mac: ENC[AES256_GCM,data:m75Z19i8VDn42N9/PSCmRzwtMxEU8NqYP5pAWAyEMsZqjVTSkmLSi6YdOhpV/KsF0LKVdNtn7w7jVgHNiVJYTEWtiNKEWv8YlCdIffEKucZ7BRzxDWOprUWi6igIvJkRUD3GIq99l1R/ow/NKx7r5xhJTcp+THpnmRdUT3VQeZM=,iv:rQ418FQ7iIO6rjegaqgxk/D4OoH2NA1SHA5ngM00h7Y=,tag:aMX/Bpkd1XKv4dWR4oeQcQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
