apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ktLJeCMPN+yfz/mnqmH/gpKeHEqMdWes07Y0lyWmpW8PynPiY7vY68wZUO5va31JsG4WKpDhZm7Fx3JD5dTmp4kvCENNV5D564pb26NVBLpVUFMCha6WIPsxHnkofF/qPdOE0m2CcQmXpsmkm8oYBiHpxTkXUTLKyTXLk+ro1SWpyvQnuNCsR2dONRjgupW4zvpzqzIZJsZnXbmwcTEPGnwX8RYuzGmvk4pGd3SXjdrVVEMbCIDsWDq+L6FxFawh2cgZwY+eNZCqcCl5rCLkAfG3M2oYMQxk8EI94zYLa5G7cF7u2lS+ZC81RcHRN9+qyYMBnVyeQa3n/+kubRbNBbisbifH185A7tIspdQcGHPrgV7wC8QgTUUoj8B0+7UU,iv:9aCqvvhS2pOvrPckrOEjn1OkOjRfkQAFdkmZ5xfoWJk=,tag:7lULSN1gT9R1FXkN7FHo9Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:IUKklXvFipnGokHlpWfU6MZD0JXVA5gw/ku1eykN0jwGoMgNXokBc4a4lJnRZRFvNjSjCNiIsQPj2d89Z4eZXJ/lrtw1Svm4OeajBHHT/9C5eZ0KOm+nrQ0ImBfgPydNprZMPVUwskGKdRDyqm7FTejrfy3Ex4olsXitcGw5mFor/3rqYZwwKQDmnt7TvzweODYyrvBLqd4nWxRCMZoKHoQzMc0jlr/8uHC+jJn2WehjFkFevwfzEWw0KEXIvV8xg6ovYnTYE2lD2OgVjA==,iv:aiiN64xXF9xlrvFMgFkOU2iWRhtx8cuDotjYGFbTWgk=,tag:tZ36OZmiIVt+TQyf/GonDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Qfp+Gj8P7DbPAspZZCKIA1zAlk30BClHaL+O6S19S+1clsv7vhSIPXl4YxPZ0i5Q644XY4QqLkK0Av9zNCbd50yRyjQ/GRmBOyEtJJCy2ztJozEMB5HLn6z0nRYgOo5YyVHoiPgaNZhL17FJ5Y0tcIz8kJZu1Fun2K0FvHClf89mb5fWMmGb1uHPbF2DwY5HgKaSe56VW+RKxlYUcvnyAHpJ7YdB92KYPUJ1,iv:gpmyK2EG/mjRbYA5HQd3syP0unn7aE8fZZn5vpnZ+eA=,tag:3gGKU+c8dzVcfxbl7VD73Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY2haU3FyTk1nalhlQ0RR
            VlRpcVVybWpuWDFMbjNHK1BFc1ppa0JNMnlZCnY1UnJVRXV4V3IrRXBzTDVtRkN4
            RXBjRW1XMkpDcllxMzZPb29tVTMxRDAKLS0tIDljcThqbXJ0U0pMN3c0Z2ppU1Vu
            anBFZEtrczNaZUFvU09lZ2FnSWwraGsKAUCbGP0NFRUqEolUkHxPsctRoVfJDhN0
            LdXTNW33qWlWTQ97ximF7T4cH+6WpC3AmNaq5Hf+rTH/D22lfWeowQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T11:44:15Z"
    mac: ENC[AES256_GCM,data:LJn/hX9SsIWbTlVnZawSEKlfawO9RTleRY5aTm/R86z5j8bMySKdljeDkSPKnk7VVM+3HpvRBjdbYG9VMug8aV/u+vYuUWLSrfNlGN3VDqhc6RHhvM2URLCALhKDG96rpNvkALs2P8UCqkg9MbQ4gzc8GOdZ2b/zdH+imoRrYIs=,iv:CRk71hGl61OaBwxQqvTCWXyOKMw29K+Z7c34WID5Wno=,tag:eyqJJFcQUhAIkYeCyHicbw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
