apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:N3ynan3oMDqdXNrxXM7lmIV0ZSsNA+oNGUN4SbJ7JlSYIOdPfKMK6HDhRpVtRry1Jd2jmsPwjn4ILij0ywx7Lt4MK3NWaMU6rukhV4sIufgpd39lYaSOAIu0RnRCEbYiWuK7wHNngvZ/YNCVpo7pTe9m9ntxC2+2SvAuYVshXXDdTciUlAKLLd9FSfDRXGEfWKWRWId2zO1jZ666JvRfulj6ChPz/V7xh8liJcnpZaSBLNaueWOH5/mieYzTcYqBybI0xatl/58j2v5G96CIPWMWvdXR/1Qa87f7P0PhPVaENO5nECsFvMlCJi83OdNI/utvo1gHg1PD1v5jPLgC7JjlhuiOi5gFlojgWcB4LRaTgbvtGXToQEqlROred8qO,iv:A/FqFi9gfzDALBwmiEHSyNrIAXwv07NRaMCD9HwQ+iE=,tag:+VgSTF4LAvpf3UdOX/c8lA==,type:str]
    identity.pub: ENC[AES256_GCM,data:43ZH/vJStuBRd1NIov0gIwjtWHdiDketgSGooP3jU0HwcBZ5picXq5+LoVbdP5vfo8BhxA3w3VysePysXtYJaQQzOXkUPQtFFz2Z9SVCXBS272uUY/QphvrbUryp6UlE5uNyZwLq5ihyuiRpptBGuSqZrE3NjAGXJOcji8wZ78+VLHak3OvozJS/wDRnRFKv7HtuiKN5iz2fnseZeOSusSNmHdLgE36iLLvZnD86OgWx/Yg+3K4frHZlUpso7ZItZFtUUDGDmVu2NvQ+zA==,iv:B7GmE4wPS4wQWUpdfhRi3gNIUjWAIjTvMQnxAHKK6ug=,tag:aLteBpv9UIy+xevwzIqVAA==,type:str]
    known_hosts: ENC[AES256_GCM,data:uWj+FZtzjPeX3NJuKPsLucryNMR+T+TAxXy0SZXlarn3pcklMWMGI5xa3+9q8b+ux9UP002V2CZmcE2Zant5pgbP/ztHNZA6sesadGMI7I+EdzUMZmtXjew83cqbzdlHuCShzDICTze9a4h837+6x3Jff18UILm1fuzo3NvrAsOMnkFbS/6dp685hbJA9FGBTNZ+POjMtSrk3bK/dfd9IzzmCW8txtQ7N1EK,iv:kduzhvhsJEgLRTM2NV15acUf9AKFvOuUobqUHPkfWDk=,tag:BWq30wTc1zF9ZqJ7dlbXpw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ0tTNFVUK1FIaUpDU0dt
            ZE5vUVpTZ1BqLzVLUDhQVVFqQldtSUdPcmh3CkJIUFdCL0ptS25YemRlYkhGeThp
            WDlJc09lZ1kzd3dCbXBsbEdXZlJhTzAKLS0tIFZjbUlkd1BsZmhIK3pVUVlBak9z
            d0M0enlvdGxTNHZNOVNLdEF5dWIxQVUKQZH17CE3GmTGRm8RUxxHXUwY+q9+sttL
            JAxc1lxidOMU7PEQZYm5LpqqTzQUytvPV8v2E5wJUMMrP3TH7QT+sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T16:28:34Z"
    mac: ENC[AES256_GCM,data:MDRO0sWbHjqvSKOpIYksx3cK8fxrwohanM2i1KVYbmEcZa7NPZLy8pKgD1ltdcI18A1He0d8othZ2h3jycQ5lBf1ZdEwRrSCbJuKi1g04Bf0Qz6jG50+wqqM+6XJLqClJw64trmoJzD9FBzLmfViWdS/aJdrw7/1I0qQVVc7AkE=,iv:pofzZ6c4Z8dpgD8SwYIP88EGk+ibP2YOTdLthP8vZFw=,tag:Y2g9TKKCYABXAxG8MYVk8Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
