apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kKEOg84ATi1vralFIbYDMi3wGroGx1R+s2bQqx0bjc33KOnSSv/GzavEvBWdUOOURD0pOA7txBSPvbv/+esKWCcgpSqa+OttPMeW6R9iZIdzOWJIy3GC1ylu2bbcrJO7NeMNikZQGf+9kQ561MCtG/ySP1W+doXanyyUPeIAmZ4YuTyKnk7D8bmy+QAymvuzcmruKcFnlNhVErJr6hQqS4/QoeHUL1NH/gqNpaJ/ipW9GMqQlI309kEIX6thjS8eR3S2QO0fozFr51xX++WCH2VrM29wCyngzIW1JKjV0Rvhpa/90j80ufZXcHYPAZCXYbwDnJof72IgNzY9lMMF2hmc3IDDZ6dmEvLko+FACLdrUR+76pOHqf/mEiXMrdyX,iv:+3MkhcettZsGn6NPdwVgoTs8i3CihmXW5vREbhtFkLw=,tag:WhoOmO18Du1WkCSLQl7zLA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NTF6ZCxRzgCAF56AlGGHGDRA0XWO65DhmhyJ4WWNF2xFIZx0/qdQTM2TopChOg2BMJbnTXtAdJlXU/t69iveYg0jzQQR8jV2on8HO9SzNPEobxAO0PzYvXgFo4tEP/zlSifjwsENhzDglVYvN3XKgcouEFjtyKgEsH3jm6NerXhAMX7teBItzCQZGCRSkDDqmqnSJkqqAPa3sVWrkor4L0gFTXf/OVONo7G1FnVk8mvZW7mSWLoaOolyI7zsf12jK3dtQR59nuuHgseJ0g==,iv:V5BxX3Z5eY8bjBTaQDhF0hensEIObM0+eyG3cNhR+0c=,tag:/wP4buSqaUrVXP/Y66vigg==,type:str]
    known_hosts: ENC[AES256_GCM,data:wfGeOgbLHoqpznjD5Y02E07jWutqnlWqyrM7cEc5n6qQ3HPSySLTni5xu5zzeB3bV6ZloWeQcE7W5XE72gtVUuGTsR0R20fBZA0lvPjA+ok9yjK+xW6O1uWML5VF7W8GTvrvworVoszcm5pHRHRudyxlXHiKZqDuVP+gi9nlZODb+zrlNt3YAR57CXDJBB6MbF6CQDR0TPUGJSeoX7hmRAkZNDkQhSoWKR6v,iv:qEsw0zZYf2J4pnxtpsMJtmLcwWgVT3J1yPmNfVtbKWg=,tag:wK3QKZAT9mrH8G2uX8mQdA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVzNoaDRhU01yS2p5dXVl
            YTVoL05UQTc1UDd3VzJJREJWZG9zRkErYldNClNpdUF0RmxwaUZJSUxnUjYyNE5R
            K2RMV2NiV3dNWGFLY0ZodGpWR1N6ZVEKLS0tIEVhUmpBM0VnbWZlNWRZTVZIdFc5
            eFRtMW8yUmpmb3dyODMzMitaOHFZNDgKymIVw/o9SLIHbZrPJf7L+TJYz94GXJvL
            qXuHUF32aMSVOm/MU//MyCR1EQ3FlmPj4NQZkZjlk+qT9pTxZmGxbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T22:02:17Z"
    mac: ENC[AES256_GCM,data:HceyNVyrCZhpx/0PWbxeLG6rBTIbarq5KbplULN4Gd0a5Sa7mUyvwKXq2TIoM+O/G+G0GvDFLcBtIHma1oE2QzFYWoBJEf+xAxXu1oazZ4l5w6ANrvfNUMF3efiVjlnGl1nq4CFS6JTjqDc3mwRSqRD7WkLnP3AjTWRDMg3U2Nw=,iv:oC4xyUN3LV32N5i2vaumapHL6TA5OSQudJCY3d7TNDQ=,tag:QewXr1Hx/kQdzb3lKSu6fw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
