apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:R14LVXIEkmSZ4eoo52KWzOxeL/9IC5lZGmbiR/SLhHMHl0rcUZvUiJ+ia/1/+yOVxNwDOSqPDHuiN0zxGMcyvh2kI+EOGvz4kRb3Fa0s7lZMWl/rG0mqNEyjfpxB3Ct9Nm31KZuUhRbK0iwZS/dQqWgauqFFuqpwlOHx+yYUb0Tryjp5hnsUN7M4D0F+51/7v7EK57iBWFQgcNOGhPPx1EWDzCBGRsRMxY3ZXgJPp+hxDE+vHE9e7MHs57AFKWIdYfMEteBovez6L5BWDNltw59cLEuYNDHG0stfxeXih7sBL5m2K801WlCffbawW3Q0+JaNIdr0eqWFjlhC8NYddpvxIulFTw4TKnoiXMF84Oh++nPAMbg7uru2sHS3uq6D,iv:oI3P98O7w7I6zDorLrzeIN75pOKig5LOMo8dpMyRVSo=,tag:/B74/kPpCIv2chFSGdorDw==,type:str]
    identity.pub: ENC[AES256_GCM,data:5xwQ8uUGDzLLX7YW99x3S+Gr7JBftXT9DZLSMTsQrKVhBP37rMQfg5cygsfFH2cQWA/b/0sbywJFXYzLnp7u3eJx4RkqN5uJtR+t5yfFa/bMlpPXMQnmcppSej7SxBIBb2fnGL13679VI+w8A4M6NMLXkN19UVKGBe55lTiSRECvza85v4Efpzp4cm6XlZX7t43ifw2sTRtWm/Ca00TDtvBzmU0DITqZko8LFlM1M+bZJD+Ng0lSMGylQrECf1BBPLennlUteafsOBI/Fg==,iv:y8+wVrG7IKomZXPSWk+VQj9HgFqWmoZM0OaRUyORu5Q=,tag:zdca8u5IC3s5zTHdVM4WvQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:dxDfv4DrneJPVVzgSG9VabcGPEeAD8wzT01h7qBxtl77xwJZvMwa/qJsRM36v9gy+88TMCw7pPJ6zp1wU1Hkaxlr2CdJt3KFfwgKFwO+RZtgvaitVNPcmj47VvWEem4zqyzMWovTmqibZjI0mD2o3sc8FBGef2yvZw/b58RPNX1jGb/YUeJNnZfWb7f70Lz6x5IbRVrbSVvk/oIZMGaLIbPk8mb48iB58BIR,iv:YzL1jt9r6nmFrsu6+w/A8AUTGXHw2DepnoT+RtFw6zE=,tag:/LWBeb/Yv6XWWCsPae5vyQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSEdiZC8wbFNNYlFyNkI2
            eEFZYUY3eEh3OGtVVEx3dUt1cm9WVlNzVzNZCnRaM2NVSDBOemwwTUlJd2FuQUN5
            NHJsc1Jxc3NYREJzTUtqODFRNGVTZDQKLS0tIG55UWovK1QvZDRlZkhUN3FtZWNF
            UjlWeHNQN0pJTTBXY3FSVnJISUU5WUUKe4BK2x4aWphmYU5yMDpr1USES217YpAr
            kFFbmmqw4WGIBUR8AhMUKMeY1IPtTvhTl0KFlLDMHkxf9pTaFVGB3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T07:34:48Z"
    mac: ENC[AES256_GCM,data:qjY+cjCuMQloCYYF9egwH3MVfc/nJpm0pPw3Pxq9R+yaHjiZio0AnklNYtZNX+8uzt4hN3FlZtFEmoOR6AAkej/jKXiDIUX8kmSzHHGFUUsYYSbLCltq/SY3kkXsORcGvGp9zX9AhvpiHfA/IC4axCoy8qAKiirBrNYSfUaE/pc=,iv:oZ4agez02/DfMD5CcfSqqjnnr3PZONUdlyvDlhi3xKA=,tag:5MRTSsYZ1VHB0JgbXF4W4g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
