apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4X5ro/bgAHA8E9JKK3U88Wr0Cgo6wn7Ihu55lgfzPzpq7V99A4P5zMsO99AjNGIMMSsDXjNrTxGtSGvhBsH2lOo+xfRf69x0DVW+8C0p6lAB9rFy2BIe5/ZtdA3g/rPCsguI0gQ+3c7MmMSc7LaG8A0/73mAbcTjMUb3DsyGzPO6myG9+y/vzzUgzW49OXE8EaDLlDC5pNwIU4d6mnAjVelkVVVFNIWjtxRGui8ZRStXPIriAiNfTo08jixZbp1ECzniC7s4i2ZeTrU91qbAdsuZCOUiySU6hejEqR7WhJLShdxO0xsbOXWaZIxz0vKPt7GH39NQs9ZL5Z0gCJtLFyeUHc919HdRysS4Xrb86DJN2BMvlt2wG1S6qIe6ZyeY,iv:aI07OYmeAs3diZ/vpvC9C24rGXNn2TLQAroOjiU9JE0=,tag:zhLWwbq4MEo77eyCwPZBtg==,type:str]
    identity.pub: ENC[AES256_GCM,data:4sa+byE6tgBgpjOtZs5rmnc3rF72D/JQUa3dVMRhgdJGu+07u2sJ7pMHoX53Nmj++mxmagHqby3dMywfthUr5+5s70GZeSeJb/eleEFM/msYpWchgrFMH6hB+iNTdJnPzYgcBQBPOXsxrJwV5ddh67JEwbyHV4ro9JZOxCxojVn5TSjWVF+xhf4FJ5YpfKUxpXvXko1e2qcae4274zWfn7Cf8AFcE2AlNgq7HHFHYKnZnIm4wMo8Y5Ny2DLMKsMKxHzjXYtYpcPvplZaeg==,iv:VupMfVFQgi8LdXjYF6frGJUb/D2kuTmZC63V9VTrLSA=,tag:RoOjzQE0K0I2Z/ZU80AX5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:7ZFsXF3UiAQrJItN833DKJcFRNGvCYYCkiz95BG9CtZborNsRsXa/1UvHq5HhwqQvVKALihmGVRgv+edSPMB9fESsObMdHM8QJxUejlZFYLYIl8+tEdT3o51CGpoC8Rs9dTBphAmw95LKX9Qsb3wjX9aAlTids0v4h99IYuAzQ6xW1HyvjVvFCvAifnp3Wn3cbss3zpylhCj6Lab/cDB2SKk+PrZg5BOdT0Y,iv:rnEa2exU/b1FT+d4AoY8PKMEN4tCkheKDSruskl5g6A=,tag:aOcRNfZHB4JCN/62HZQ8fg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0enJ5N20xOFExU0lyTVQr
            a0NYcDJpWXpXNTVnbzNBRjRSYVdPa1FIT1dRCkpFZzNmL2lFUU93cFB6dEVjTWE2
            OHNGZjdueWNJdjVaZ1dSbElueHp4dkUKLS0tIDFpVm9zU1JYT1poYjRycXpCYkwx
            Y2MyQTdEVGJMVzdXdUtIWVN5WXdjeWMKOUAhH092tDLQXsC7+eZZqIGsNEmae8U5
            Gd8h2t3VyNxPyWbuXsEFLYPUrcRJspZvUf1+niN6Z7ILp2hLoojl3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:54:14Z"
    mac: ENC[AES256_GCM,data:upk9zhNLeTUZtjACTmEsOOJmUfdqVB3HGoLiCvuZW5+nJdo0YyeTb9z2wnmVs4LY4PtWMK6B6e4l0O8ksteWHBZmaHF7q7ZvFPhDJUAb0N4+p3QQ0HT0IHBUFukaNvbrKGpgt1jEkfReeZHamsga61XUUbgAAWBdMYlj/Uqa52I=,iv:cgPN/iJhxgbfZqayIAsw0Vil9JqSwy89YsNt5HM8Flo=,tag:VMt/stGGA/PRPpXFwORHog==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
