apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:lO0xR0h1qRZmk6B5hgBPtfz+x9lHddjCdonmk8yVMJhhJ3AX7z3OEVsPXAPMX01J8npaALsq188Mklxk2gix5rEifU8TEU3UDDKlQAqIixUiJF64/nMphBkJlPBNU3zlNKaZ1+i2bF9F1cQpTKPIrZTlIjKokj51m+xIKDhwPP26q0swG7FX6d5DYMVUxDC7TzOSx3VXmw3c7TXo7sWsTyh3WafVtHsdSM9dQJRU1sWlMjM1qlu0wWSubmUF1EFvpsctXo6pKHnn0ljODkAnU/6IXlT36OkU/Fe5iyksi1Jclrp31AX4p51K2Fmn5eSGFkPT/GM0Ua/hUs6iDMIb/GoYIx8H6CzJwJvsnsUBMtIq+tg1cGriO0O2U6xo1Glf,iv:Y52RwFhzfPKutH9XCk44WLMAIQn+5KwqrTGJJdr8BGs=,tag:qUg7Rz8AE6EyhQPjPmNW9Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:qGvhtNQYViqtpa4lklMH8t5uR6pBc5EDxVMyaofB72pjB5P1yr+wJcDuZLla0hwiXMHwh3Ty4d7SBHsbyvKvUGzKXTOYXIZhf5s7CbVbMSATVnLpTtcitTSzjdqhi/meOotn8NqkKAT90UgZD4vbCFzxi/mac090sc3FppOM22tKnH+lHh6IjAgJ93GQsXgSGOnO3EYqVcykxo+e6As4zHx8rJNewvM8d659IaXYOQVom+4PnYVjvzEKmVMs5Um3A3FFtGrVjVRxOGMj2w==,iv:ML0FZT1r0G2/Wo13zUK1QUEc1FV+ZdlsllMnbPVl3/k=,tag:NiwbbR7cFcZ4U77Sx3WWAg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ihsEiM6JpNuYQs580sf9Udf9NMEEarJDjhYSTwP89RLo2rjIoRkYRV/yRlLhgONkKZkzw5ZM73fBO2xwSXmP8YDY58hJqWt1B4NPzWTPiZnj36HVbX2hNTPxhJAb/LoXGvQYt1Lq8qk1xGw87IJv4BleThy2kVBJz4cWpSJ2gn+iKzkMOzJ9hXtWBP2cnGKpxBOyrWLNGimLHwLk1epfs77BsS5y747xvAfi,iv:vxQepw3x5qTcnScvjf5wIIMvmQRENj6nKooS0hxVzvA=,tag:UvxcNz3q8fFsdJvVDgzpOQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOFVsN2xhcUlpUXdHMklN
            VHQ5YVNCUzhUK3ppSEk1MEJyS1RLY2c1Rkh3CkJVM08vREtVTEE1QWVqak5mMFVB
            T3JHb2NwckNTR3FoMG0yWGtDQUZqY28KLS0tIGRzTlRhRmk1VmdSN2k4a21vREts
            RjVGeUxDOW4ydzZ4OWdVbkhyaWN3d1EKarENYPluUKrRLKEAvaW6iWmTCNRSsT/7
            1imfXHRUdkmizM2GzfV4AiEb88/Tf3p9cU7YjLwDwZYwdkAv2NbRhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:30:33Z"
    mac: ENC[AES256_GCM,data:QcmYHEw/2RaC/rsJBBlrjjBaG/E38C0kftBWORKRF7BwM88LJxgg27U0HMzrZMWFixvoLo2TuVxrruIEhydeC6JBRFbt47YB5B30iyNfHIpL3+Ozs24Tows4ThBP+2YaMCjxb/uxMOmKmPgWTVIzU1i5qoudkR/fRpX1HhSwgSA=,iv:VJwERDJ40+yWtgdTTxwJKBQQDy1NEUSBkPAFp8daEmw=,tag:7jbEtiHF664f4gd9aLXq+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
