apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZURwNGUwseat7T/xf1LpPv/M2HQ1CNlcXW+X+5oDqyny0aKN+oSylE6LcmrSO0SYDG5lygfVeh/3Kimn3GrUnj9DwCY5AQUDWp/9Tv/uOWKKXXIHIkIP1RPIQpCp63gpthDqyzE0xjkCk6hpvdX10zhQkLCUHsYyQgFcHEK60NlmwtTrovKjMQSxlDmFEeCeWG4CczAQcvhEwWmAstdKolf8yDI+XgikFsNeo7H5iQIdrIa0rwJ/QrULluMR64CFwIbomMzzcIZgKrnxiNIdIWI2hCuc762EcUhRj0MEXTq9RBS/tLm9L6oQT682DUQBqPwIptZ8+NDnC6gcs3FXU5fjzSFtHbJI0H11UT4foVBIekKhXmvt3If6+pDC+w9u,iv:eiz2cTLLYAuMuApK4bdXC4k7zoP3hydrEvrw44wAxuU=,tag:T6nD8uQw2tq8KtgeV3PqGA==,type:str]
    identity.pub: ENC[AES256_GCM,data:52QAXNjdoyKKwJoR8uxBJXKPKWniCwORZivcnbfz/oIfrCdGZekC2vzFvfi4kMojflrCXd+FCnmR4DIgM7E+7Ofsf3S2xildXQUiOgEXuq7JECLooqz/yOo8qZtLupEC1wjWprOT+Xxtu/JNn2lJPfjqcBNysEzVeOatiSrTBZPJuCOLrfpxc9B1eMKRfaWIeO6c56N6eGuMS6Tbm8mNepZfBClrSEUb1Y7RijLLhp2iDCVozU+9oBy1jtKX+9iEO7jK/dc+rlDuvzGSlQ==,iv:XTlK7lmeMmBUgceCLLJGbaU5oDrHtA7TkwpbRqzhUrc=,tag:8cMAc10qd13jGezoWBTeAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:0uTGH/9g/3QMSvHBBNlonA0Hnr2JX5WEfawS0cL+jS2JrNj40Ap6VznGiIBTBYS6nWRzfvyo7LhbTUfoXaZPrkrZ2lAGwY+ESI55vlrEdtzkVRsBZ38zv+Q7SzEUXUjajkON2ROJBLvI52bCbad/CGDjmkQZjF+/e4YC/iTmKiCdGu2gLJ/z4eA/wcLEhD8Ffzgn+7YriQXygGDLD1scoIthy0gAZXKs3Usl,iv:WFHZ/5zyjPxbKCA6PPCSF8JFyTA6pTYq93esdG2UH6Y=,tag:jJsHInBTbtK9ogYYyFJMAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MlZTYk5mcFIzMzVjR3JU
            dXZlcGt4SXJNWmw5UDBEZTR4b0pIenRsa0drCkdLTEd2alNZUS85RjgrQzlLeEZu
            OVQ1d3A0ZU5xeUMveEt3cnU3cTBudmMKLS0tIHRpWkxaQUwrV2c3ZzEwZzYzVHVG
            NHlMTWRvUHRHUElUMXp3SjhXaUdqZWcKy6G3Dcw4v7o/L8dVOCI7qK1s7Fdqj3JE
            ZQhz6HdRmUZbmi89sZxhdNbXtRmfWpf6ryzD9euFcmNP9XsDTs8vnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:12:13Z"
    mac: ENC[AES256_GCM,data:uC7vJvWY/dUluEHTwXzX44JZ2fBCGsuTUxyiwRUrSJE3xfla8UkOZB8HNzSe/oMHs5x09CIw/doc0hWWvX7XGemzwBTshPhSGRpb8U7VtU9q492F2g/j+aII2hENKWbX4BU7fUAQPdQJKZuOMzwCRtsUZPsdzKcjAlJroShkuKA=,iv:YfDHjZBToDbafeH1GMipSiHKOjUMFbZQ9XuyKJpYhWA=,tag:Gs7Yan0NB5b0Kz6XCWFx6Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
