apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NEpXdTesjG2IwR+fnjulgOZ3U9rpSyNgnY84y2s+1ULdxSkmLE3xdz4CVOcvh1FiT9J4hl5dNuHZ77jO6tcrl0tytCWyqz9iRsQ1LWzUJeLy10Uy1f/vGnh1gRTx38LzWnWKebM41rVmKs0nMfqz9AN5M9eTnb2kLHAYf81MgOTXgzzluxjcW+6wc2Pc5PM2mS/Pk3tH2r/f4wt0a7mlcor/gtiE2Z13uUnSvVJbgJpr3z1m5GqXXDqzT/RngnmeJiqq2L0A7inKzlo9CRaIU7zrTdTlo08U3M4xqiBFX5TlCZE3vJm6tunoR4LTY7nt6eL3IzrDNov2tQPqYYvSxAzqXk9hKId9K2nLU+DrHpCuZAP01CXlJFbWdsVdrIHE,iv:aeU/TVqRzdIdWLGV3zDAeiF/XN+7hqTGWlwWvuS7HcA=,tag:nEJL+k55WHtAGoY5ReL9xg==,type:str]
    identity.pub: ENC[AES256_GCM,data:pnLlFMPCpCCKKfrc118x9H49Ah31DsfKyXFEwvZ1itXwwJsD/B+cVYTNrdAxASjbpzMOGKTSXruhuCJSl3mFAbKP8bCvG8N+AYeAJz2VoV+g/A/aRIjedDzWTqojotCKr8zCLsEH3c24wopmK1wn+wucQqa56GQzuFJem6Luka76PFe2WsXEQUBq1E9Thc82eAQyjjtIA9PdtO9l7UP7yaFSJf7DkT8ODmoKpQ2Yp7C0SApLe9Q8Slx8vQh0BLB0jf/IU9LShqXFsAsSdQ==,iv:keFv4VzO90Q2wCTODknlQ0X10OHO4J4Z3Rg7qToZz0Y=,tag:ETnOLspxMPtPsDedOkW0GQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:mZnXStWoYweE321SzWTKbhKl1wHtQRGsk6WlLPS8QHlhA4vJeYRNfI1ki6T4OEcUY2aRDkVyI9eLuqkQS2iMs8gcJjHxzNBgEbRfQSit5yiT9q9u+7sgQyu16RtmYQiml0zxAlbEbAeo9l/MHO4mtOVk74xPB3y1LkwB78yKM5VbI9dizqVXulzD5jWoHwVh8cWB8/FG7ET5E//CXjqQFZWHSz/QSMk3Lo3Y,iv:ntL9ebvro61Cz8IfzT0414xy+nhAAt8NLEJmmKL5emk=,tag:RRiscicXHUV9e3rehKeEFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WEZ2RjhqTmpRRHd1Rm1E
            MHA3OGM0MmdsdU4yUGphcTdmRzhzeVRQb1NBCm82eG1lbHlFbDZ3UlppUGlqekZo
            aUFGeHFET2IxcEExNDZ5TEVKOCtqRGMKLS0tIGY1bHVkdEpDR0dDRGpyZkdDT3o3
            QzVOalNlcFl5M0pRRjNpbk50VmpRY0kKfS2E3kwJRCqtVp7pKZ8Kp96hnZv7EXVD
            +0rMVtJu6ckhOh0QPHgTDGZY9T9zIC47CcXwxMYAlUATdslRf+Qd/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T07:31:29Z"
    mac: ENC[AES256_GCM,data:K3FCyqqsjjcWfc5zBvdMTekkL/kpJ5r6RWsskZyCIMscnPN/lTlEttxc/V5zn6i4MCq+hEM3Q5ryQ/5R0PQJy7XPWzGmme3cIFk676pBG8yTicXwVc/gZ2QFlG/D0zVNuKqcvLdpoLpk4b1KmYDhROGnytJXL6ncQNET2LLGNN8=,iv:8EpqRFRMIgOqoSX+ibQSB1l79gVS5hC4WQfxJTsJSzE=,tag:m0q/AJWTZ+N6nF4iusrXeA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
