apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:n7QDBGk9I2LWSRxZhX0RAWAV58ztvNyFS7+9mMg9myvR6STHG/PBfIOBhYgGXEQ0v3NWp9hOtkWus4csWvDuQHp8vs+CDGyIOT/fl9dZdIi79qWit/zzY7b7lLnoVYsUKBwmYyuwEMSYjPDy7HlUYO2HLxplWIWR0pjZLttZ+97t/48AWzOkDpR6NEPhOdbpnMDm7XyI7odsN+ucYoSjOzrGDihFDJo6Y0exlzPT8j99QGsJ5aqovjGxz2z+oNaMNJMBoviOtt/0sTthy2SodYes07NtHN+b8jNl+aEMME7EfPg9yeR4mrpXAxs8BszzSgcRI4C/axrt0cBNSTASg3lCenxkSpjLcrabb70DVCrumxVOJEqCZSSo4gM/Gvsh,iv:Y1AL6hngZWtjIs/ujPpDL5PJMKuitJ46NRVUS35rYg0=,tag:VCPwG7OwQnUCa+NcdMpiNw==,type:str]
    identity.pub: ENC[AES256_GCM,data:hmllpebNPGezM5MwIojBwXhQ2VztLC0NptFsHC6C8oJwP76LbZHQt/+rYfD7hCH/RHJHW2NbTdGmYhQvdOnd6S7CyWcgN4MHOuv0iyIGcoFol6oqLsoIhVZhIJ1L/UuoXjeBVyoWVVbSbV5eQ49fovTHMnlFNMvkX4ej6LFa6x8EphXD75CkgBStWj6PXkoZDVavDNuuh9nRfqbKVxiB8tb9ZqjSet58dACEn4zHIqXSyJLX5YpVakc6aR2rb/VDFq+o/1YwnDSBMzZlwQ==,iv:QKVs4UTYzipBaDts5la1wYh5mo36HSMjzPQB89EtnzA=,tag:Rg5JzwFbUz0AgQwkweeBsA==,type:str]
    known_hosts: ENC[AES256_GCM,data:6mrU0XYwt3FkgdlAdj/q29B+Y1EOt0mBpoOCwIISzs4ck0aePBdJrq81n17QDi+vbf8k4hPc1vr8IhZW+mfy+GqN4pYGhSw2jvgvFAYvgYEhCZxeoMtRmGUpZcO0H3Hhrul0ePFZDBpUnP/Al2vuVAC075Ao3VxMPzNjZt3zSVKOAy/qaLrrtyUuNEbC62B60wo+JQJ6O3+zFgHznenbNWWT1ahVD6TJmbMw,iv:zG5lvpvwBdLEdDb++moVH6PRyyZq0gzFanKy2flD+cE=,tag:6kIQ5iLETNiiz5rJlsf8jA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ0xiSmZYeHBFdUJnUlZY
            UDJaRnR4QmlLOGFaM2FKZVliSXV5cldjTFFjCnNGWXpwRjJRSU9zTmFJZEo4QXRr
            MlI4SGNXS0J5SzIxRjgrbElhY25PKzgKLS0tIFVwdFdNNk9IcHhyU2tzUVQrTG41
            WXNPYkVCN21KelB4Z2JVeXZjcGxINzQKYWoIBwXjqumzMuf6eZFRZaLkLR6+4HQK
            NFc90y/hUzwvsjIu/EuD52TBy8egFm8hmTIFibuAUNddvJy5j7vv0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:50:03Z"
    mac: ENC[AES256_GCM,data:+3tVsnmK1UPWpCa0hnuHry737iev68eqNM12ouKlVZ585aCCZvduP8N8SwKaF5CS16CMeME0YF4QWoEDd+ABoc2uzXGzoXaeiy/pkQl/zGrUNYhHd5+xNUXBfVpTqjiYSJq+z5SxxvfM5G0IyMC0sF8M5e+vxEFm5Mg4TkS+kUQ=,iv:VuXdYA8mden9+TFKYtg7fVPLtlSIMQdRP/cgmVi6WmE=,tag:fFSC+LlFD+G0fhGv06pAYg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
