apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:C2xisBvc9NhetgHw10KSz8vgM4xs3lMIqutUZ11HbEoz8m3MJ6gYMUql9gYScy+UIjPi6RKatGc49uwaiieO+tXM3KTOMbMkwMfiu9tVY/h+LaRYr+E9PG/l3I/7KHAEJp9Q30assgSguvokbDBFbNP7FW7lgbGGBJaRyI9MnReTJuXjXcfxEvuEVxcMsThEGPxr+WldJeUmXhcoIF6HWeX9SQD7rTUcK0e8SfRbQmSjMuEGhl9VV4vnqv6MZ8SvQQnxZaViw3ZRGSfHGdkeuNDVFvLL7+tu6DHPHRqyW6CWkaMFQ7563eCjgQzkXK75p4gz9QH335cyVKgojtDxfQdn0ZPvhgCklhIC7i2OHNpOVLAj3jr7X/ZI6rt/uozu,iv:q3gOf6vjz2RNtPrA+9JBN6ZSVwuajS248Qc34cSzwYo=,tag:QWpj0ICr4qcZHV4lH+Jd3w==,type:str]
    identity.pub: ENC[AES256_GCM,data:za1qestacXXbshOq09BG7uJijsADMUOAQDkA9+2OY+z9iy7SVLsblG/73foJwNfxIfzQr96veu1ScNa7fhDXHgI2lfdjN1qxoIayRptbnooQDnh8Z7MbkJA+IxQAnBJojjEQcvGnCiDevZX2haSoLD5nrkQEMNz23Snzc904oz7kcsvmIC1keWM7jpH7y7lUgknJtGezMv4f+AEZWiwhCfL+yMxAyfrIrrIvlnFvGfZSjIhWOxNnR3iE5MKcEX+/53tDvO1Dj4LsvV8MrQ==,iv:VtFqF4TSBSBatWfi4av/HyxqaZ/up1XnL6GbNSNQFhQ=,tag:mL5PKl2nEdSQnT0adJI+Gg==,type:str]
    known_hosts: ENC[AES256_GCM,data:bxJi1IRRL1CoBI1ayrnyDFhqaLVlCky+QtUaxDDnTM2aA+LWBVMSXFkERlO7XVVw/vU+RsM7LGWwT1ukkicwJVshrvpi3/kydwWDEmW0afKrCGywro1N6gd+6wKFtWZnhPTwlpvC6sG2XWkLYMwVKMVFnZYwzi7ocr3N8QvFP4QyaNkKP2HqrCQX34i8bP9xa0YNe3f1JVPMyVy1CntfxOebq0kiyD6YRcxM,iv:FhJKvexq3xBuwN7kqMxMaoCoHPbZkQWDmQFlYBiyi3k=,tag:g4MYSG+sfdugAexBaXp0Vw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOStTK3h0Z3JwelFmWm02
            UWF5UU5MNlpJRGtIN0xwS1V0UFhWR2ZxbFZVCm5id0dvWVBRNFh1aU9CZ2M3S3cr
            bnhCUTBvMHA1YkVUK1FoQnVRd25MTTgKLS0tIDlidUxpNUExMXFNUEE5V1NTSFFI
            L05vbSthUnIyN000UFdCN3V2akg5eG8KvKS9TyXTwiQdAb/MxfscWOe5JgkRolVg
            cEyC8seoudJQXedxSjdItJawp6L7yM3YYNFIyBdjtI7AUtrlLsEqCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T07:34:19Z"
    mac: ENC[AES256_GCM,data:nJxf78w007GTtZaUIKAlJLFGoHvbEHol/LeD7XLqnEY+zkPHWRmB/pqO5h3k3YfsAxxd0Cn+P2+RDRVokXJQm6rPJ6kFBAl2Kb3OH0j3p+B4olXr1t4EHUZAHf0EgRy/FFA29B3w6Mhn0plb0tDLIWNlVZEC0V0DT/9+tuOiz84=,iv:rYsfbEaon7LT29Nxf5Afx9FwDhuh4BgRTCkHwrhy4D0=,tag:CgsNnBEmu1gS6Y+2ZnroWQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
