apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dG3sctqAz7ZKqT7xl1ZeBPH8hYIfFZqjzDloaQOLBjpGR21FnxP4lWngp54rnFJsyGPeH0e/UK1Imq9ZeiMKyP8drt5W4Q1NRp3FUGJ5sUyr81bvKcc7/djppbrJLi21a1BMKFLMEmUrY0Aejcds8zu8+zKGK5iOyybwdgjXoPL1h/zX369/Vd5/UNWf+5NnHTIe3MREi9QYMJLg8UizbdwmbSybNlyXOknr3qmfC2/C6tDV79Utx11q03YwRLUKHQAC0y2NqL7m6rsPIXMjYvRZ7q1VCnyTnx5bZG35S5OlwKPOtL8pkcaQQRSScmFkrfdRW3IpyWSyp9uwEMIG06TmDONfDLNwPybjZI8cgLAN8fg5f43sRK4/v/n9ackH,iv:iackuLTjVpU01A7JHSmSQeWkRxO2qLJrefpxeQ0tAZQ=,tag:xNyNp/EuWsX1E17a3EpydA==,type:str]
    identity.pub: ENC[AES256_GCM,data:br37V52bFDKKLVLNv93mDRshEQyWaS24bU11sXub0On6/xHVKsSSo9XLY6lYOXz01YB6YplF8IFZF7Msn+zJuhNe3J36G/z6BHomqbheD2Of+GmEZp2xLCLfhG9DRd2gpJExoRlppNwWYKk6Ibfx3RpSpOLGp3dCr8TBJhZQ2v9YYJ5hW5dsxdAzdoVHmD3Vjb4/ngk40Nh9+1ADyjHe4icd+0LnXJ8RFftwKq4zy/oBqemgMNUmXNUp10PBos0Lj3Uu3KrMwjNUJWVJPA==,iv:tWLnk9VWxznsv8j99PWT3PZxNu4qzN676Dmu/RzLhas=,tag:jWa968wg+nc5A2XqaZxJUg==,type:str]
    known_hosts: ENC[AES256_GCM,data:/6keREnV/b/5ojzXgTVxXmv/nrGnPkwtAw98o+KcjbFDA17932Z2k/4xT3ryyBHeuZSZ6G82wMLHCafaxMLCYbd02NCxQ0B+IZGQZM9m5nwpIr9gRqEbtTfNfejr976hMoe6NhixFPJWPKy1RwwKm6CRtmN2+IO1qg4q/BbJO4MILZRla/ENv1uxau6pS1y97ecuklRfRIibCprO28USxP/nfR9lxLml75AD,iv:cmGisnVeehsbdhuGi1TqljsKVwE8buoEVZeedSTSqa4=,tag:enTAZwcnF57+CUToWtGDXA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMUE0Z1d1MkFiNVJFQjRJ
            TVBKNXY1M1lOYTZicnJBYzlDZUZXa3AvSkNNClQ5dmQ4aG9DRHNHeVl0cFIzUFhj
            V2M5Q0J5UWgvWmN1WmdidU55STY1NE0KLS0tIGQybVJDVmI5UFdyYTZKYzJRSFUr
            QWozYVhxZXRTTHRYd3h6RXpCaTNOV2cKrT+glT7YI4cBVwRX3ULhbZk4nNuL9KAd
            j1B8sHCrhlF6l5zKnDdfSTolrp4go45vGk1m/ldlIMTSjG8h0DhvnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T10:46:07Z"
    mac: ENC[AES256_GCM,data:xJazDD+El7Co/gj/aLdrtpCoYdPnrfOkcumYbZ5d+1F5lrnhq/C868//kiNHG98o8msRKwQMESHSNVkLNXpRTYnDAiDYbVdwWkrPpoPwP+NPOANO+nrkoB2XpJM6cnN9/f80/CVAd0fNxhv1+ALZWXgh3RELDW4cqOkqR98DsLE=,iv:XgobhHWVI0kE24B1ofdfZMho/r1I4lgvE8JjRuBQsog=,tag:bcn/W2/+U2g+f68Z+b+B+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
