apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xAAroPFcEPqTw2d6ANqR3kOwK8+MU2+WKXduIGBFNcsqYhjkEgSZWcbfV6eO07nRi6nh+HY3hRiTZim++BlVLKp3so0wLGSafG0z7kfdkgfocTWf0lFBXdeag0CRcREh2GZCNi9528dfRESo659Skf9XUuHq7h4mTU1SXDZ4ZrRYq0OMU/hgtbRmOKeDN4qyRTEp9SE7F1gbCfM1eFFQ8TJdtZPkd0LRpPVuDV9XsZo8JtNRsGR59km/e68nbnuC17htxCxCkY+kdcrWAVnTgXuRTDaE1aLaFvLg0NZtRmCa062eni39qrlCun9bhFJcIIUl0NzPmlLzQINVWgrWL8qkYtK6n74pZrbh0TWK6Nmffm9/D11dDn/XkrqvGTSG,iv:YyIFYVK4hoGNY2Zou2wOe1LHLec2TyAcLrv2VBEosRc=,tag:3I/uAFhTFXScaW+Y0TIq2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:7/BoM1+Ypz+aM9bpvk2Q0FxSuCqthvJ3Nw332L9dRpV6dQqLSGG8oBJiJFqQteLg8Hq5W95ipty0VirVDqfoN4tcMwtKB9FvTIxco58UVJwn0/tRe0U2DlLfAG5qUEEf7vwKqu2Ba5o3dwIkr/VVbpNNgJO8oyb8JkKQt0i4D/dzxXUoyAB6pO6TEQq10BOeKVLcLPBSgaaa0FM2MiXQnsVA6OOi1qmxS8ZKJvo1NGyMue2cgjUXTi9AJPMAD0l/+8ifL297dsGURkcV9Q==,iv:3gYaY/UWRb2eGdUSX/KcPoYjCp9u/PmUNCZY+nr0Yec=,tag:prRPwtyhAeq1X8sd1CUCyw==,type:str]
    known_hosts: ENC[AES256_GCM,data:qFPzfJi1qX16tYkYCObrbmtYZCP+7BFcErmuiOS4AGeVRTReObMgLq+DeqTSLMHvBLx22fTNsDzX8vlUOXpv2j+S/7w3pljqYLsD3x9meVSr4fweWECyD6U44AWp4cnLuZIzLMARVRkGQPpijmmXROtHTBSfBplVEw+HO5Akd75zwMrmMryaWXiqNXgxVBTklSRC46WERlbFFM522hVgQLOIarqC2VqwnVZJ,iv:dgBA5a9mT/TQgoKMOdUAw58Jae2f5RReJvaak3L+YUQ=,tag:A8wMjsw+xnjXBpjVTP97nA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSzdHZ3dzaHIwa1E3SHlV
            MkkyTG9TOUVpK2JaeU1yQmo4Z25FaThrZ0I0ClNOK05pdEVSV3RHMVFsR25NOTIx
            T0dGZEVPV3VjQkFSZ1huN0ZGMW9sVVUKLS0tIE1pTGszL3pqWmRrSzRQMllqcUwx
            Tm10UkZKcGh0SmZnemFLWDdVb0JYWWMKbyyDK/8of51leuMDM8HAd62NfrI1mOiV
            9QEfBukezlJWcQJFxlpftf3GhCgxzBTGiAvGsRzQlKX+vR6Ezp44DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T06:52:22Z"
    mac: ENC[AES256_GCM,data:z8487v9mwiVnV1ygVSqWln24pyz3LuoAn4vapeR6dnM4Jab4e+Nj8yPqGmrmzh8HGvDGxQUSXBRBm69+T5e1lQT3CmsIoCC2CA3auqHSyzVFRki/m9h5LJAu5Ja2b86Jj5pELcP8GiujtrsNxi6VceOaf5f3mowATQMD8eUoiCo=,iv:lcfsK338jazf2medXFgBZs5vXtU5wGcOQvy96HBqmfU=,tag:t7hMylpVmDzMlt2qMLxD3w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
