apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6/PCihoM/JcA2syhCMMsLgUVZhKSLHb1wwnVy6UjjsnQCclPD2ucTU+N20ZDi0l5lDUcqGMJr2ofAg45mnu0foF6UN1PLGbo1o0jlii0yb+EPXiFS1oSP7Yyn2+jRH8pdISVnSJp44cPCrVu/mPl9inr9+WFug/D6a+Kd53gltEbJ5JgIVRL3s8VnotbF7FPD20xMj8Gzm7G/3YDlz/ClCLlrLakSkQ/hQgPa/TFyGutQhiLlNX7JxNjH9Rh+ZfGxMFXGggY1+jD+7YAld/J24NkX5p0JoYe8dOUm00xSsvs6QCgwlzQrKQx/I7oNcV8JADk18l9fXOvAG8Wh5iVP9xEIqsZKz+Y0KFwNS1E5VyMaWXemLODjCa4uaRNGyH5,iv:lk3Xhg083g8HjiXUxbyQB5eOtLv7UHwWSh7sNzFO2tQ=,tag:d8C+fjRXHQSopXJ1vt4EQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:OM/wSn6v0FS0P+HB5NWxHptuLMLU/B4O8DeJ2VwZ9dceOExuJfgS2YeLc+PYD+w+G4QBF6qiqsqJrN4d07H6UrEidmCBDe/ao+Qh103UJjghoUhcYWRDQpvhrtFGcdVhAgx+XIFxr+g9qNUDc9U2qYheStaxnPcBnHgYT629CCPfEFHxfmB+h6WOht3LnQhWes5OI5OIpgSmwVg6pRTFpf1s1/VLcjxbnBAjL9qxY8iicdsNNjRugvEev3cRnssY2E1xRIP55GDTENKWUQ==,iv:eaJhkr1Zx3XiVdi7RzeX8gQuA7LHXQIUAmuQS6BUjz0=,tag:fKcEvFH95dap6De6JyKJGQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:xdROVSsaUmucZgA6RMv9cr483WexdcQ2d4h9ULZOrphRHvvFWNQ5DT+Nt+VyiwkrOXIRd8sfF/GBscbnRLiJ5cvu6HtDjdbztV8Snf/5I0CzN3H8vA7fAkDMUSbD1odswMozFL2OfqyHAPvfjt8P9QokG5kYETxaQwkmokwyswA0ETlp3dXN5I4GCIbiB7eDrQmZ51fHOzRuo3zZK/MzKRn+8oh0rLtMat1y,iv:KlvmmRFTCcMnoCuNcF9c2L+Jna6LpQluSFREkTYVriw=,tag:JDz9FO8g2pngPxMqb4AHnA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN3NjTkwzcy9Sb29vMkNL
            S0RGcFJEVXZnRVUyZVlhR3NFdTJnMjlQWEFZCjBBNHE3aUVPd3lpZ1JWbzJ6Z01i
            MFNKYndkZDhFSTdTTVBqNDVuSnF2V0UKLS0tIGE2SGRBYnBTRWtKT2FMS294WVIr
            dmQ4SEN2ckhOdkNJekQ1KzJaMm4xcTQKKRZeU1Bu8A/n/odZQ/f7kCiZ3m9ijFHJ
            7AwadMi2zuFslZGs6MCnT5ndDxsLphMNvgY1mv1VQoYEM3G0jiRpsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T21:53:05Z"
    mac: ENC[AES256_GCM,data:HpYSf1QcUn//WYxNqIdFcmZ6kI3U7h0nSpdWceCfaLP94MF/EU1LP9req4sOpcjOFrPjzmxWe59V5sSBAH9lGUyFwwCxhahxpxDxOVwAAb0tvH7icZdKjKxCGO/+hxwb6aOF6esqIF64CwGlSPIUlZFPzI6IXKTJ21/gfJkbRMY=,iv:48ksWRBHFRPvg34sHt/MLZ+fH9L3ENJctIO3H3Fy37A=,tag:TZxKKjFQH+21x7n66G6A9g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
