apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:TtmocDrEYMCeL1twK2Yr+VX7PgbPOkFVndkNbQXbwzw53JM24XxoWd0kDnZFPvo3UsVj2FUNAiSp8SZKjdxgkojbMjVIfejuivhJwjygW5/voR74PlOfx3TOVrvxXRdx6DwqjLbP3M2LC6pYGRcUA0VMgJ+rcPmF/KKJVcF89ck2JlrQYZRiEi3QVKi+YMhINME5lpUbL/0nbR3YdLF9hvt9YbyCTMvEMqmeeIfw978166mxB44HhoNz0rdoIFMKml375qvxymnLukKbKIXtqXKElq+ZJtlWpL6rJ9Vp8YtrmxbOvk1Az4mwLjRsf/f3P81UsIdfdnk/H5+UtyAfFzHOlWgCqIHD+y7U0ykCRZtHTltjk1gSNBOg39ziaUiI,iv:o321lpJc9vBu3HG8Ixz6pUy7YS3Q0O44+p53VA4q8Hk=,tag:wskSNG1RZHdeSUIJcvmlcA==,type:str]
    identity.pub: ENC[AES256_GCM,data:o4LuCG06u6IGnDnhWtLmWBqvaL6hWG2nCeTYJjkZMK3kvzMHOXd+X8+YdFcbfT/ahGwB9Ms+9FNKAeqhnxMtGRr8Za6ETW6lrvhs2lcCeSD7D3+bP6JbHcJ1njcnCZvthXiSxSP0BygThQCshfc3P7brFDcydbAnNd0A8tyd+GXm+CQCt57f11wZ9iPye3YemXDguOfjSHdmg+Jwy6d/gHlisPdj+v5sBLMF/BS1LfP+Cc77n4DwoOHLz6mL22kr58z5Yry4QxgempDNSw==,iv:83tzWATxO5VZiAsFkC5Vweq8kAcYLfHtVeKTFz4u8s0=,tag:8BC53aIh930RFGUek/c6IQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Ev71L/rZnG6S3uzS4/M9xrGTt3/3bkB14p3YVshzrQJbpjw23cyB9Gsb4Syo2tYGvWKNAwX0sqMT1RcLCDDnTrr5iI3NnPCamzWNU9wyEiBidlOPvh8jg+BA9eZU7qCBny+fo4qfSKZE0FauPa0hTbCutZMl1GcP5ENhFLm3oqUrFf/5ppUvYo50nqsknizeJd2DNmYCQQ26blFzBbBtJKvojyIrz42dJ56I,iv:7FizfkFgd5m0qXFt3xwtdcxNmUknE50sQN2C/LrdCC0=,tag:p/xM3fZfqgoepIxHBME+eA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmampWMU5OanB4VjhGUm04
            MzFyMzJaZlBUVnpHTWdxN20xMlRndGcxNjBvCi9LMHpaVmQ2ZG91RUpISG5iZUpX
            VkZKM0ZmcXgyT1AwaUZCMWZ1MzVBeTgKLS0tIGxNWGZJbmpGNncvSnBPN2dDUSty
            NlFzZXlNSFJsTk8wZm9XUWtUUWg3R1kK1/dD8FNfYlCYBoYLQUMiU9bcsmGzpWgA
            yacUjWGGJAsrZVA2Md5U94u40D17FTRokXytwKRsE+GXOCprP5IqTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T12:58:16Z"
    mac: ENC[AES256_GCM,data:bsepyy93gZkU81qbFuveM3+iMXooeH3c5ngGrDcehQ7amCodBmhy6AMHrtEvkCDjgztJAHMrlx1ZbEquOR8Y9Loj8kmuAaEcSlKyQM8uCZoY5eodQoQ40/ztGOVulwKeYMDL9yLotjnu4Ko0HFZ0a0Jvrj5LXPFDAYMOPDzGXbA=,iv:dTlKnqY9N/g/aNMnneU14m1zfCAQ/kY7depT6+Ffp2Q=,tag:gKDXaySR5lXOiDuxS7iXKQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
