apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LwWdCi5dUsqRw+Jzh+yHAQYedLZ0IiB1odBnOsfU7canpsl1HACeXxTXU2CSf06y9Hc8ttSafTEpZtVyWy3uRv8Pz/Uz63O9QBylmBtV5gXrVtWHPZMjYpCc3yW9XmQfC4/j/rBtqJQg6HNe1EshXnSqoJ53+Ua2DJTCpyBlucDVGwqHHUQ998fZl5O3ElatEcJlhYrtfEbB744KQ7j6v9okViHrUp1MZexHLcdsrcuwuMAubGMCWVYFmO44sHKrLiuzBGfQUhq3BtCXSO67SEoyF8Vf/eNI/6qaAOBZPz4/mM+ZQWv4dzUj9FjvyzoPG2HkbXpxqho8G0TCWsJGyd25zAL34uTTfbhAimmwFwfRfQQDlT5zSAxeG/B++xuj,iv:FNPXWY6Ie4yeSRpXLmWBJQ2VeYo1c/Zu1g6ktvyvsFM=,tag:PFaGV2iJzMX9Dt332oBv+A==,type:str]
    identity.pub: ENC[AES256_GCM,data:tb+yQMfb5OjkI9maRBIdcuO0nxvc74OZ7nVhHKrUiWIhO6nHs584xhNJ7tdwBD4Jz5r6y67UwY0TuL20ZiR1QFxTlhxR+Z84xHo6NJbwWhCS4Ih06+nvDIH8kLW18qD688OIW063Q7kCiJ7rrAmVi7C7iiZO4VVrCMWCGB6Uo9wd8sL7YbhCpk5ecaxxyNnODn5YR8eo1G3JYpy2mjW6dyBeevobkteS1Qak4EOWNV29r0G9SgQn+foVmmjFTeWABQPuCkeyEDT0f9KO/g==,iv:qUIBbcln8L1tUOVRJ921eXtDjR2s83QaceXZx6TQA8M=,tag:LggM8WmQvfIudBGBq6UvAQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZzWQkZt0hQB82lxPJ0dlXEc/J2VR7s1IRgvmNG2brb6wOyWxFgtP9bJFYmtfNISF48boZMbgTKJf+T2fONk+odg1KCdhwT85e9swMUiTjT4Yg044tdGf6ahpOuwVAWKlRi20nLjiX3YI5ywwZbpPdr+8UD2H4aGYFs2QnKwyu5HXGc7DsgFhEnXWvuiQItB1rMpE7riX9YGfOLNoOjFHnW2ZRTiFwKX0mX5F,iv:Ki4usoX4YrZhtWOT6DjDTiHoXdxtRR8fIXVsBNO+jm0=,tag:kaL/eT2ChlK6eCR5WetWww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR3VDSE83UU92WUZqaml2
            b1JNcEFIQmVaZ2pna1k2SFV4UzlwVjB2N3pjCjVjR2NxY2JhbGkzOVhpY0g2Wlk5
            QUVZS25VaHhxQ1M5TWlWckZrdTVrZlUKLS0tIFVBT2pPUFpIMTNpNjZSUHlaVjk5
            VHdEcmJzMEQwVzlVd0tXZm9XbE9GRWMKLf6tP8uN/RvoBbYcEzDoAr+5q8SrJPCJ
            iUsCqDiHVQES+Z2rcdsFf0Os/Ew9350E0OWCi7VNSqeOJlUKaHEgpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:30:52Z"
    mac: ENC[AES256_GCM,data:TYT9cCBrEbXuH8Iu6D9+onHzQTbS63zan+GpT1u2FoSR7I3QdUDkpzr2pdrKwEB7BKVYfgAIxF0ES4tdVBHe9ZF10if6hTWZ0csynrB6fzKnCOovu3y13CDEB3ZZ4KnvnxevrvSMFjkT1GLJS50r6OVHfiai3nyj5q9R0j3dqcE=,iv:PMhrDJcPyycQGGvPMc15C8P63TamV8GH0p115qcexso=,tag:oB9CIBvGf2SopbdzUle7lg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
