apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IPgDqtaaR1Km1C7Px0XwrifflHmvzwjevxMKXW1RXvP5/gT/j7yFAcnXYLoQZXb39m9ZrInK42Xz6SYISEcYk/DTzI4Ep5eUTqXW9AM2hqFc0DKCZywSL0hn+tR9TE3SZNxU+5mAuLDcNHfiMaC3mj9WIbrFF6p+md1JXJfJPelrlgy5dhSaFD4mLqHDOwEcajNR7hG42oEkRFLIFgs1fhmGmX4AaUc5XPlKqSMxhH0xz3m+T12NiI908ho1ubJIJBQmPBC73EQ7hoh1iIs3uIWZFdptRDR+uCVVKLB3s1AK718+YXqIo5wCKgELNGOvFbUqAtg7+6UocszYaD00E4O6THzBOXIIbYzm4CNDw/Kh1wGXU2g4EJ2+eKvykaHI,iv:tih8eiHGBTQvdszj1jDCVMd+4sNqxue5xVvjPTxtr9Y=,tag:OQ4LPEsju8zRb2WlbemQXg==,type:str]
    identity.pub: ENC[AES256_GCM,data:rRbig90S6L1NfBxEZ9qPrsmtaFmf/31I6XwJ1C9DJQrICvHwq9i8B5lqALdrs1UDLPTAjGEnPggUKl51yi1nPoTuQ9nSVHiiyV0sMP24UasumFretrhytdcbs0eCKEdjgNuNnxKYHoCeNkVBGg5TUEgfeIw7ZtZ1pifILw2SIcuWVr0zo8Jz4rCH3in+q+tgYRNzOnQPni8GzovQAs10rXHwYcMVh2g5+44gyrCQt5Y4T7QnDkb+sCJG4Y8kR28cPGjAWDmohLyjVG/Zcg==,iv:a0eeYqdryMy0MWiy48JxP6J17v9vj9PjnI/sqTFUCEM=,tag:CrlNK1/JXbEGsW3VlfKG/w==,type:str]
    known_hosts: ENC[AES256_GCM,data:8IlaSI51TrVmhpb41wPVH5j+1Dmq43hFJ8/3d9W7SGR8DghTj87aGH4E/gh8fTIiOpKRMPX5HoJxx7EbNQIqcCi1cJHxtCdV4ELAvjuew6PDqATLExarqBEmxbd3SwItK7K8kKc/U7B5IRKd+Eas66oRJ2aF9CyyIg/VE1qMHdw73eQIDmUGvO50OI0wtR/7Z+Cbko8szhzYyxGJJ3hTmEpUhAKMW2aIFMSR,iv:aCezakzJFex1ckZPPIm7gzg3qIyYaW8FFQdkjqOyiT4=,tag:d+gtNIb9YYH7V/GWnW9G8g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdi9aY1dYRXp3Q3E2V0ZJ
            a1pVYlZWYXpUMHV6R3hlVEFBcEkrbi9VdDNBClpWa01XQW4wRDByZndFRFBNTUNr
            b0R3TDY4SnZicVFNbit0R0ZHK1FQUFUKLS0tIGpzVkQ2Q1lkWjAzNmdHUmM5MFYz
            Tkl0bS92WDZhblNveFJ1M0ZYcXdiZlUKJgtKWzngKZjDAgXuvknWLuXYwIgaq7X8
            SJTQic4WFjxuIjVv5aTSFzxh9yLR50S8tJRAHgx6VeHQG2cBP6zn5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T11:17:06Z"
    mac: ENC[AES256_GCM,data:Q2yWdreOWGPgKOfa7SNIeNRY3neKyfmYwN+QDb907DEujSSXiAHO7mq5yVsOJQiTIjenIxRzF9QS3keZ8uZ0UoyEfe5y+t0oUKqtYLypIgPQdntlikOxP/zkmH28QeV6TroAxbw9l1CVW2d8pC70BEQ5vcDZ8bzwbqSrkCRqUhY=,iv:a3vyijXU0Slv1EAoss/Emg3B6AAwkwSh7oMH1SSjkSs=,tag:0thR/vKVQubbT2WPxmyb7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
