apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QJwWL5gGSl6jIqpocfarN+AtuQngiwM0ECq2Kf+dh/hktyGEsQ5V3rgtRDRdhWIz8BLegVclwbcCXQTldxqUmlql4TFZZByN3Zt4MKQGlBsFXeChUk6Hw2flvAO+ISJ/PnxY4pkPmOjR8ucC90p33qRfhT7KKX/0GT8notPZrr/sXI3V//dXGeGPb6W8tsGS+XidU/Y6B2MYymwc6olIWYqRxp+KTeQq4pgVyo4q8SZPfkKIkvHygu/1yLB/DivIrcKa3b6z+H9/TzOKihPNJCu+C7cQIS8ki99b+Y2BiFSb5YbziKj0vvWf7MoYhwwEa+Ts+2NpW7bcqn6g3g/RCAlK0T9Q3y0gYCTh4py/QRKrs1djQHu/JLftFyNTIUeb,iv:gY/HySkgmT6ETRXYGHmbr7OsCUd7E79uKCnD/nBl3Qs=,tag:VvQuDQWjV0HlV1icNXbWVw==,type:str]
    identity.pub: ENC[AES256_GCM,data:PGEm1jJ+Pd1TroPUUWuC/uqjCckfvWl5WA2TwQ/0hgcbxeq7cFa0lU6/wfArKU5ol+zy+UiOkSCaSJgTHC9pnbZCElk0cYpC+vvV/8v0yZEzoE67Ss97aGHrQu9zNJ3iHDuDTrDTHKlpi2eUYcWYWB2MPK8AGpzIxbNU5gmlm9ibCShBSkuYQN5rq++qQ7a6lf4Icu2bXgs8CdaywPgztV+Y9Lm0/1XXJ9wUGmUsDUAFjHQrhy3F5/HNw/xwRCcfVldaZjmsVcxb8bCRDA==,iv:3r67RyabGHIs+VdOOpmNuI0kEgeBpHylSdpq6230KMY=,tag:x10QHwGpxo0aJytvYau5Xg==,type:str]
    known_hosts: ENC[AES256_GCM,data:rB7KFmF6thITqWad3yqWm/QR3bHEGz80M+ODnJPbDJ1MCp0nOu/kvNKAKoqWrTVLDf5M4lwj8bzUv0GIGHDSH4IXwiJaGS3HQNqKeU/94kVXGOQWdKIrLVQ9M6XM3eCC5WdGAGUDVft3ZMBvgWTy7ze9fC1Yvs7Byg0m8d6nl7qbDhW0zhXYxWfcCR7DwmavInmPFO8yrKfYv1H7N4okv/+t+nxnFgog0tSE,iv:tZlLi2poWFQjH9u7PQWRhlApiHEHbiOXyBAT1Knbnvo=,tag:FaYUe9OX+U8LbnWn0fhbFA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbGZsK2YxNHJjcVBLcHlH
            UmJYTmcwWjNCd3QrVWk1NVZHVmxRM1VlR0JVCnFLK0Q1MjczSFFXY0RSbk93YTBY
            c3RjR0RuQ1d0SEY3dmJrQnlYM0R5NWMKLS0tIFY4eDNsWjdNQlpSTXpqWWhxYlZF
            S1gzWXFaL2VzUi9YUUptUUFIdkVZc3MKlU4ZXlEkZnnnU2DT/siLaT7+FZFmHxCB
            3donfxnWb7DOahZiOIMHNsigsKtAqt8Xr93LW5ppCWRymora5WC4Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T22:27:32Z"
    mac: ENC[AES256_GCM,data:PzVbqqdSbky6JgCreECb1cajFTOWtATM+dtXfTXAmrnFTBh5ceOTTALMOyQEw0IG5CxgxMeKPw2hVJKUNiTTV/U2GPLW5C8RYS2JANXsHAE7/Iwf3mVwztiPACgAeKEjELMFVryB9QOybkrCm0pj/9EdZedZWw60H/ko9oLYYnI=,iv:qFfGiaJg7LWjCs73pPZeFaQ9Y5vXMsvhhEJt/RwXKPI=,tag:tlD+0/a4RAdzbet5rED/Fg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
