apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tJorS8GlEKEtJDQJSTdTmT1pk3ROmvbMcKdNGpozIDciT+VrGJKFm0lfAzMMgpui6/V2q6oMMeRKCSOLebvq9WR/74+Lp9ipmWv8qai4ZyBqAdKUWmsVuAsjezBESV3d50OLjNaiIGB8TthjhDx6PbVMd1XWQWhgZzDWUkaWicRA8kESlmGDtBQemqBtcdcVK4NV8RHCCh73kBp0dtyZGgVS4uZVXMRt89/C/vZRt1N14AiOL4tOp3M1a3AKMqzbSkLVzFzQc44Y+W9u3hQjl3DFIfZ2OibqdZIKtIouAgADTIUGosEpd+/KiD0ESugLv8AyhNeYaiJYxTeqn2y9iXQUgOgriOO+ncJSqUTtvl+7aHnJ0nAG3m53kBxgccS6,iv:IKnsCIFKyPhpxA+YhPeYkmG3dn0XCyoJztFD6V8WWv0=,tag:AmJ6im3gkqFOdrhxXar6pg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ljXcgu074ttqROZ+OzI22Ren3k+z8+aI5YPKz5SV1HSST/rDKkojx119hEMOwIHCvTHu/QSryK3qmCXWzhyGaU3QGWNd13l/FqF9jepEgxQnLVJxXxQOJn5PI/LPipIT32Qa8XoUv81xGwKy1dIUD5yQoyea+9OiKUS63ZGgSQW6NRokaeT+v3X47C0u9RwZmVnpY3J2IJ2wpLkHfVg03NkmP46nirdYaDVTDALA2Kw8iEbOYYIpwunZDjhSF2Zx4Vs0UnMQqS3cfir1GQ==,iv:8d+ZXpQX1oPnwrlVslTcNrHU9GKXEDAprxI10RfPbhM=,tag:InTZDGzN/39tERXIOxUW0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZZSh9CMwPsuRAfP3NbqtnztiCdRET04XtpQkx1N/zW5uIcgEnhJGFIx6rK/wpyfseGILxqzjZv/k6WI7VJsuh8tRQzWZNiADWU8I05iJnnMGWKiQGlqNDWWPZdB6K+rP6HM19qT05pvcHIcchYDugsL3pwKaw1lqI4x0K/mVMlsmDOyPpuYy/u7DpSwS2Yc6V2Xeux3awNg/JQCoNS4AOXy9eiUvBTrTwTjs,iv:J0XAdK7WqijsWRKaJFMZv29wsjemQpWVbOn69+nnp1s=,tag:Mrew+hXLwspxytmWExT3Nw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwT2duRTFlNFl3WlpnVHY5
            MVhsNzlMQkNyK1RVMDBmd294TXhnUHIyTzFVCndLRXBOdkYxWDV2YUtxYUZ1MVhx
            RmVFM1drT1hoRHhJbHBuSTdzY1RCK1UKLS0tIENodEZSQTdHc1NsSnRCSGpqanpP
            S2N1c0FGa2ZDSmJJd1ZnbEFicTBXMU0KmCGWc2DgN8tWRtoNbm3moEnb+G7BrPyO
            46Wddl1PWAkwbxFtOOe5lLMeF9ElEMYzBYbvDvHHWv7B89nipHpPUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T11:05:49Z"
    mac: ENC[AES256_GCM,data:4eWbX0OgxbywNDdP5jEVAX/WLjFJK2bdwW4BL0OfYN2bgAaydtmroaXQFbgDHGDEcQO5eKyVO+83xF2yXP8OnyvqcGIJz6gYoBZtf40Vg9vBHXYbdSM7Uti3FPCk5yQTf/nZIqiSlGAVwyE+i6Re4JVtPE/+9YEo26hooQ862KY=,iv:Lelf9+eI4q5k3xqYSopMx6CG7LZOBl+sJckmEeVsM40=,tag:16PJey6Z6+7LcWil415JpQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
