apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RqAlt5w2CbOLn1y8Bka5NI8P3FbXcciMCnrEhH6dGO9S7cCa/Vc3s5ZfLo1+sD6xzjot2HgLRlTN9J0JIUrESQrvn1Hrm+UiAi/M/lfnKfSzNV1NfwEM++Jh/zFNysoyLp8EOUFd6ZVcx3ksENla3MVCSPHnNMqeMX7hSzr2faV6NrPzTIjOgzmwSXu/XLIwJy0+sPT/W2QJlbwKVWacx+cb7zXhs0oK+QKE96E7GZmm/Q/mAx04EY6n2zhRd58SHXwvr3MhtF582oaUwav5lF/xkwpA7K3iRz3aOqQDyJX1UTZ3aYQZSxMAWWyeS7LNQoUSM/+WbxuTKg6AU2sT7d7hraWYsCPb3wAzYoUmCSK/kEyruenICtpXfGxUvZMx,iv:XUR6Lq/eJ8IXIyTelsq2KIMxKr4H7vhZZLY8O5rW9A4=,tag:a1AICV9u4+UIaSRGVWG/Lw==,type:str]
    identity.pub: ENC[AES256_GCM,data:oNbsxxJqcJEZ02hgl2i8KPvRTrOMvzX0OESNh3PdOrg6CXyS3FNCfL7V3kmvRvIhAmc1iQzQGW88x3k7l31+m7C+KQQwbozv4rYeGilLXM2qnApq5zR4GHFDR1pzAFMfdmHd0djqtH3Vj0JAQtFTk58kdSXrGbs3s1vUfV4hodHT8yE86AEiHDohPAqviTZFYqo0zcp2lOd7NRK4truPnnzhOkEwn15ezfRNPE6Mfd2cBu21yK0oAey+mG+pyWEDINI/1UuWbCqgpflvrg==,iv:yWvT3UNMKp9guFuFBDxKBilMnDHNPJG51DGJrlcy+wU=,tag:gfI51henDEXrCr8+b9J52A==,type:str]
    known_hosts: ENC[AES256_GCM,data:nMrqBAV9LBEVu9NNFt81X9IF9qCvxMCNlFrHoFMGAkCbAFUU3/mcL9J6+vwLHg0k/F7hZpqpRv4wuZIYd0ZSlqQ8dBTNAu7HGVddH8YvTVaw3tD5OKHkkwIgq7geb7DX99vKPL0kK93aszpNzXTuQgYy29+cDaf25C/e41Rrem/tkq2Q1xbhttvfLTbfPaznaKsIyYsbIHqvylj5GgbdeIsPezLJNvkHU4MI,iv:8H674o2nmC0tPac0D5XmlX6rnUjyFEAJBj2JoWFGKbI=,tag:752sK5SqQc60v11jBvTkAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbHllYkJWVW5PNzNZNzdB
            R3F3cnVoZHFEc2xuZStqN3lHSHRkdkZxNTE0CnRwTm5Oazk1SHR3aUF4N3FlVDNV
            amROKzRvQ2txRnNmM0lTSmxMdW9oRDgKLS0tIG11Zk5rUEpWQTBBTmloNlZMeWVh
            MFlLRGhXaXM4M2lxYXZEMVlxb2hZc3MKhOM75Ll+p6ugY3m7CdfgbexZKkoD0qBM
            ENsg7Q44UJTtXxL5SclRk1Kasc4z3z+KQsMhKT0QatbxLHnhZGcykw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:19:08Z"
    mac: ENC[AES256_GCM,data:fNUrBgMaRtYORYV4HiOIe4CuwRKVibSNaeY+jn9uxZfBgy2b/RKT+O3lmzsLBcDaEb5sZUMSmPc2HAciFA3xegBOuKtahdwlwn5FBUWNnDnoVNaJfinMJr37SPOC0AZSERSXDw8ZaeAJThCF1jA3i1YAQl9PogSuEHdQuX+phlw=,iv:rO4W8oDX7uJzDdowqeNMBcxBAqe7PRTHdjEWAVv6DEw=,tag:WWAWb1pDjp/XONxfxv7MaA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
