apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:eb09wtg56OA9nAnCz57/xpFWuIP/Q7u7g2WQfAypj7lco2vmMBuWhzVl6bKkVzIFloq9uLPOoGBCpc8cfTPgz717fi8HAspuXInxHfRFOdttAgWCqIhbt1HfFooW+nmaLTYlCIjBidAD+2svrw0lW9fXltMKBsgFvWMc+ajoPnbRmLyifJgJgIHzWxilzRbFvFFfO5wcyO5VUk7W3LPc4CQD00e+g9gIy3zf7CuuKr6/+nDGS0mOv9bQeuYepbbPemlk4qtBo/mIIHzzVaaAVc8T61krHxj+pDX0wTrLV3PsIu11B3thfS8Ocou1VL6uB+FloX2z1Kp9u/+IQTNZmwXXJABLWpqM+mgrq0RSZqDc6+7RrFbcFPkQRWObuVmd,iv:zgYhdOLhjueOn99S0kmvv/lkj0DnC/EUsU74SiBfQ0k=,tag:ahD5ZwQGaUH5uuY/SjqFHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:LRujI70MvWByDUsNN3+h9Bc0vkTpqnREVahtqt8/hM0ZbKAuj/kmKmqzUsD+wMzzaoPSu+m5zB9xPwIGCwkqPM5wysLBjy1TjwkGjaG26aPSMu9h2Mj2qmLLNCVYowKBWV5prrhbJW82CEnnzlxtfvd8NSdA/WbK1OKANPTel9vL6eTsymtqxgfhrDT+f5b1k3bEBm7kqJbrBiFHMwWUO5FDHKyyBuLV9FnCanbRu+KvHHLVl/fqtVZKKlQUWxn+A4yMjXGZA8ysEnbKVQ==,iv:jt3X03Iw/KYxz+RSw2HkX23pxcQ4ockzGIRYpRO8xK0=,tag:aNTcJ5y82XftGnVsZjOCBQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:K+CMc4tzN5GZyfVIPYzGEGxjH9J96mYKW4EG6D6TE9Xjcm8tTLll1v1bEK4xUFUK848bZRv+dBU04/xqASoFug0d8z+dk5ZPuV9BHhP0k+0+8pgi0OEAP6K7z0AhWSzdTBddCIDfNOZAniftkTRu7aQQBvJ87h4Dh7JfbC5as3IjSeYTwlLrXBNX7NpMqnO4CYZHZ0mfm9J5wQSRYRTU1O9KhP3GyekJ33V5,iv:QlPzEVruxj9mATGzOa5/8q9qQx8ounkwZPEFUkKZxJw=,tag:vyhqGjxQv3DQc+EeCsuEXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDa2JkZmlSRVcvS0pDS21H
            K2YyaTVFSFErM3RLMEEzZk1idUdTeStCcndzCmowUXdTWlBpblZ5UnNZN0xUOEdj
            L01aT05WenBtRWFFcHJGVWFncHpXRjQKLS0tIG5DVnkvUWFNMjJEZkhtbVZwc1Jl
            UVB4OXlYaHAyOTJER3Y5ZHc3Vm1BVlEKGECU5jcTYRyrVanmKAllJ2k96C9O3OhL
            7u153tN7plKDjNiVlpiC3HsvfO+6Vx21o8UGmnvSdxUGov5DyShkMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T19:48:45Z"
    mac: ENC[AES256_GCM,data:FmMWzu1w/vLHsWSy9cE9iq1BmkgVrzCVPzpnsUaUEw8Az8JTLCvjqyJ1/gb7UnNRUQHx4+1rDJwzHj7K1RdKQxNY2Sb4Sd0FKarnadWuereYmhM3+N7M6qc5xVfcD0Efc3UCBNUfNop/JYLTgULLFXPwTrDMrOO0mEjOweva9K0=,iv:iHruZLhucnRougYhMWA/b1/jkQs5CodYPE2KDg7PWRU=,tag:eQd3N+XCoKuJbNyk306z+A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
