apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:t2WWvw8Aw7WwvjvIUaeaaYO9cDaES9voefvb850Ob28g1EtOtJRAOb0/y+myWxXyBkouGSK/re+Q0/INpauTCjB5/VBabB5fEhEG6fX0So6m5LB+FvFCZVaV3A5V472RLvwp3bHBOKsujBDtCy5aqMr4aF9hk6HMztIq3RttS6vu6uB6wP5pfM93/TrME6j+GkU0WVPmvhDnA1SNutTCVXkXsv8IQ/wvn6RT+9sYt8/PqhXuQZ6eW8GZ+P+OIAotwJCDnuR9a3Bl8EpxjwERbkoDObdyitjEFtxrKTV2Cw/VCs8KiXCrL0HCjGqU+FbRJcrAmi3mwl73u4DJFNmtg9Rw2j3jqlYBZ9v9R4faVSvMD/w1KM+HIq4WIdNox9nZ,iv:H0ElZ1S3UMhvvtr8pE11VcGziu5PbhfYUdEiKxBTFmI=,tag:3lzoeEW77LQUTJO7jWeayQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:22/UyR+whNPdGsucsiy9C5OfyLYquxIFnZ4POZwixOFfeQdJM1eIP6CGbqrY/8F3teq2Jh/FIymE9anWrKEVuQ089Rn+DcT6U6TqG6mr+U7dNK9xVsYFLPqOJ970b8cTdb5+9ibuIvfufvNUvzKPCg9FTxPqgMWGbSBrskUtElULGTtzzD4v22NoQaeC76IBGvVDvFPUAQNC8KmDKq+3yLSZiugaBV6yYMEvq3K6qedQP/zvYIndsiyvErs1mIz/73ix6nbbtCyTHS3PnQ==,iv:uRpIeVT2B0W/nVwubdyLLsnK2BkGLnlAWXR3h/dIwSw=,tag:24e/FLV/UjS0zBjwNazJwg==,type:str]
    known_hosts: ENC[AES256_GCM,data:x2HN7LzkZ4026z8rSiKHrkpxAz1ulvhnitfnbJUE5jwlQqINDmoZ2g9cXZ42JY1/b+radsg77zYI8afYfoDpSBf5ysE+zYoxypiYjFaiLWzypWgabIQTJ1Kj+dbnRyIkSXI+83kRiKKA6JdA7HwwhbUL+b8oBGCVFpFHPc4QVoYprzsSPyQQ5c+LEGqHb6mUKyph+qDPoQobgVTKtsTikUkbXuSRlovxhFrH,iv:1uav8Vn4gC7nVCbuDFMs5wU0uQsOMb3YaE3j2SMsyo0=,tag:BI9rsFEa8CN46kvXIaAlLg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQWVHVnNpTFNKcU5NQlpV
            YVZ1UGJwaEtpVm0vc0Q4RTA0VjIydjY4MzJNClRGcE1KZS9qMzFnVWxtQ2hhY1hn
            ODRqeHlGRUIxWUVTd3NkckRDMUZaZVEKLS0tIDlkQ0kzRjNtdm4vZDVQekNBeVZ1
            RWF3MGdmV1J5R3BNakZJdzAwZ3hKY28KLYFI5H2gpkDM6V+wj4fPTk1CbISLzdb0
            jO4reqRyFHZr1rvQ7Mcw+on19G7T3YSNCacAw443YZtFIzbjYP6lEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T08:38:55Z"
    mac: ENC[AES256_GCM,data:zn9a6yWnI/3b4CVFNqc0/BFd8ZiaC8mBdOoAdaGp7B+2MK8i04Hg+km6xYCdP3VxEIaaImBSE49t6cogBeZi4AZQwfi93v7oKbbTtq3OwtezRoC/yu9k1Cv3OLX3UangOsY0HzXcBF8/GL5E095VH4gs90BRcsRaDFAtl8SfKj0=,iv:0lQNbx0bYPJJr6NDDe+K/OJue7V4SIflSCBvuxHhmRU=,tag:K3zOfMQoiea5C7EIEFuSZg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
