apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zkGhTJN0y1QFYQ/ygLGePDLked5GWaB6ioUPF0xqvCty2Ts8UoeOSSOTY0BIx7DJBKrIf/Jbwrr4Tc6QAT3qvLt6K8NnvoxCBhLS4l/FbrpLsXR0pQ6G0RI9EBCEhRk+xM/TUIcpyTcxF6K2ro2dg4x8BxmbITd/CGEUw0et6rMBUR1ICHKPhpgcNjUXBZmG9nHUlZWddMv4stnFa3aWrPqOpACLP3G+mb2NWsNIr+6FxCOY+qBBW5Ay4JVeuwnJe2p0YcNpzRjAmMmGvRin/8LOOVjGVRAcn1V0LNgEqJ3JkUfSaJNSK/R4FehyTFUnjVnouz+9s/gBB/0PXFKjmsd6kmFm8+WyQagbUSs19OIh6KmB6IaAdsNS0fzflXFm,iv:CNQs6hNBn7Apd8rqQmuqWrk+5huEjxwJH7+eAISlXEw=,tag:A3xaLus0ffrZ2P/10GXezA==,type:str]
    identity.pub: ENC[AES256_GCM,data:tXI8G+hyeU0jKI7QRx0zpwYVU5srn6TuApNpa4RjLfj5vvZM1W5xzDxbwcvy1AwihtZM15Jf2ROBw72C8+rf8/QFsTYcRqze6EiLeky+DcxfpCpe/jh1NnACqOTRiV7CXBBD1yhG4skIc7+2UpLHJ+0dSPCAbHzamXoicFOHBa2qisly7cCj5HtGsGkSvTy7hmBlpO4ndr5IA/nhGnmJypAeTab1fGOhj5fXbSSZloJ5C4ZHFXfjQAzBaKwsI4ZKoSKKyk2grufVi5QwmA==,iv:CNSnheIg/XOEsrXilURfqV8h9aJdXY9MUBkzfp/BC+E=,tag:v7BynrfmiXcgwuilTz4GLg==,type:str]
    known_hosts: ENC[AES256_GCM,data:98YmK5/O/W6ZR7bM5z9SVL3tGWrdwnqM2WUPm3tVmWeJbhVCSAR6QOBdxVR27Lgp0D6OBdOVEp8bthZDfU8gxGDw8QJNASXhrj9TwIs6VAWJTVj5kzZDsDfvBzHdaD4Uye44z1sDEfEPjFstjNblCYk0tN+CnOXfgxDXerYEnlDMSSGyON/FCMWXdT6fSgnuuwjIxB+p0IoIB0/1GptK13BiC10bAMpg1uqn,iv:/vNa5vexwFKZdM8INg1skryrInEqOx3IHkx2HRDD0Y8=,tag:zUaFEJbZ4rQwYZ09JohtwA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3Y5NVg5TVlxTXdvMkw3
            eEhlSHdYSEx2OUwzOUV5b1NqUzFwdER2cmpnCi9DenpQNzFZM0RaSWVleUwxelA2
            aitFbVI5SisyNmJOSTUvaDJlWitnSzAKLS0tIFRqcHJTTVJWZ09QenVBdTUvdXZO
            d2lsRkJSRHg0TTVteHR3YmUzMXZnODgKn/XDiynKaTU2CwN6g5NDAnhA3xKTxSqL
            CXgNSmTcLmlxP4u89j3vyru6pJ43MscNt4llGcpMwVSfWlL1yiEsAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:00:31Z"
    mac: ENC[AES256_GCM,data:WNk3o7dHxWPCUrBuItxSKMux9K1jQeUja57RnHc7puBF3tsJ/5Zazj8uNUdmsoxadkCdzp5CLy86aj4W1ZOepsd1OOXyjOQqffuGbBHH61CNbfNqqJhLEFCvSGYf/mBwE1UJHnt5uzVl/cBvUx1y0vk0XN96IBzmObzhgxh3XRU=,iv:bWlAvy01wWxNy4umy5+GfDjE94E+cVqp5MTsuQCS1ho=,tag:OhS749tJR2yacr6fCMmDxA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
