apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3AoLpehv3VM2zk/yhbMXlEi07mTVNMBNXUfM0wa2tEPPSez0OdAEaUEex9Lmd8M3yCTP6uCpoB4Rjq5F5/WpEssi61qgX7qtO3wUByzeecLIV6AUV8YZUEDlLo6XKd1WcpriWuLLihpSbXUCviF+l4bMJJv1UlSc/Fs6gN1/AWTswCkhYJDxMXG1M/Pek26OPlbnoO37SEje5zldlIWbFQ25ljRe93Zq25F5RGf79rBARWWYKvJ+sORphmvdNDEZN3V4UTpEEYOB2vBFdIZ4xNWN9351goFrASn/7iieBCWsevlAgkLxYQDS1tmseT59gvalqTjGLXE0dMeyrRT/4CPVRi+jsa7WEIj8yVx8bNLB5PVlDGFCoiVpojeaLvKw,iv:Es9ysdEd0Ndk7ZF7PZz9xPN7sAAH/vFUgMlJz54CNZs=,tag:ANDETG8TFM1AH2/SzaNa9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:BbupSCHG4uOXX9ICcOyWHqKHTn5LVnSq70qcBdnsn7Yy+IkWEyRJzdKg8BQmekfdltkLsLG3azCpVlTca9Lzr5Be0RL5P1fhb/fkudbKluKfh0VEkgb+CrT55DK1PB6yfh8SAiyXnaQcgnQMaSXfwGMidgOuA6y1LnN7i6SFOuxzrJVPwNqgnV8ae+4O/5PQWedVpov471wWb8BSND5+JYTxeaasp+yZMaW6Du49KCdUmAPf/Z8wVpBTEi0ZwX8rQoyQZruJ4hRDsPQgxA==,iv:mqmYj0BcYvq3unpivTyZKa6Hq/k2ZT3UU65Awcd789U=,tag:H9AMfF2aPPbWQWlEefZpmQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:R6dQzy0ldMS01ZRO10rffCOWb0JwbMQqYariAZS1FyRmCQVVaE1cmCK2tWywbbQF4huXdlgdGtIKklbtbWw0bzNhHfh2KoqpLUQwresbZYZags64k1e2kJNVupGNLsGDN4B9IiVUGBisbibiNlwvwRjQ+0cwD5zi5vr2EX1JGtJNwyTXdSYGVL1BJ3i4EGQSdk/Dr9FDT0T7AY+HO8zaIX6bzUMlgmrXdx7v,iv:CWb+MDZzANzsUktbp6PMDopnYG+OLvjcF+JknZWcegg=,tag:Jcwstc5+n6bQIw5rMOw49w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOXB6V1QrQjVxNWxrcWxL
            eFpSR0wybWszVXg4cEhYdDlDZk1za0FzaFZNCnFBWXVsL0dFcTd2WVBDV3d4MzAv
            OCtRVUVLUnRnYVU1bkY5SnNGemIzME0KLS0tIEQzS3ppdXJFUlNoUEFHQ2RsdXJW
            NnVhQWowSE15RkJUVWh2Vy9kVTR1VjAKEl2J41s/3FY9F7IUQ3Sn3B3Mz9nDZWSe
            OVa50Rh5Vyqc/kgbvkMBXhqUzkjv0+oyajskn9htiIWfKBIkKGPZYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T07:40:59Z"
    mac: ENC[AES256_GCM,data:LTL4NI2FtxpzUmkNxsr/SBosARTyKGPnwPyEgsT7UpVtnkygxb8eWxNm7jrh4oYu3bC1CHf1/fcRA7I4d3+uqetoBcjAAUYP3C1wHc0KLEg/SrbFQbtlJ5vIIjgsAu2fC77BtVxvv6qLI/5AYEWNkhBO2/PKezxqFswThiWwVPs=,iv:XO18xD0ru5mcxETQe2frjso0Q/V3M1i/imRRP3M25qM=,tag:6/Zkdm53vlaaK/1asRSd0Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
