apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1p4k+Af5ZRrWQ3cQpDIjrWR7Kxl6lLV0hYqx3yxy1zN75tBtf1WoCvHICRz4sYwb14mZ18fGPFl2fi8fYIbEK334yXn/jx20j9qLwOv7SZHIbEtxGYuwkNYzw8lzLSunv24Mxzfnn1t/NDgDpyu8h7uMK5uqQqbxTPtpDtI1e5lKMHXZTNNm7c1P6KXzeE0QdYTkwZbU90T5dOC+oXmH3RL/3QM8qItFxAoZ208+u3hNn5jlatKw0eHZi7mjVLDsRUpFoyQRulkibR/7xEixNptNPXqGbLyXo3vWU/tzdGizkMOZ9LmVBchQmiM1AzUB5ZTUbCgvSASV1a+BDL9sjbRHxNZdnNj7pf3ErWDC1T4ufz3blRKumGJgoIdktN8Q,iv:F4qi80JuomxMkoE4n3oUmwjt8Zj9NTb06vKFCAyHEHg=,tag:eJQHLbwJ9daHinfuk1LpeQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:YLR+LBkubPYZKZ4l0qxriQfwo54+bP4Z76amL/AF33ZvydUtkcCzCqynUyzBwe8F9EAVW93m9LSTpMYmNSwA9CJEsv0QpsMavwd6gAr+1HusGtOZ2I0P4NIIYvAkxf3PZFlghFJwR7cpkg0Sm7HVt6GveJOcvoMYjH7SeyhWMccN+P7H/VZKvebbati0gkE+NKm7OZnvwG/H29QO3j4WTl5U4hbGDlJbyTJffdbDE9NlHZD9nk5OIBgwU7A7tW7UVDT25bBeI+mCAC/MHw==,iv:aLtGdXbX8f6UsJP+r7o1LH3/pSyv31PoOx80k77h9Wc=,tag:Ac9qVZL+T/TYL5GFRzAd0Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:fA9EHxIkccsh4hoYvl6wv+OH0pcgAQkTLlQvFyaNIHzi1DkwyTpTbwag8uOKTXCdbladfuFU2sEeOgMjYPzECY2Uhz7V+gPz6mFms7qYobKuKxiDX2AvTwu/K8Kev3Nrd3v07Cgkc5ZGEBpNRIA+IiU7u6lEyC2tWSoXfk4O6PIYqZWEy70U0I6DzKmiWfcI8Tcn2zV0VeJEP11btQjIgV0o1CCphozd1hG+,iv:0BF3+228IfzCKoXTlAOFPCAofCRGYhQX8OTjU+/Sb54=,tag:HVn6qozMnQ4NoeCBV/FbPw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bUVXWU0zbmxBbEJ2TXc5
            YTVGL2xGY0F3MlcxY3dINDBXU094QVhlN1RJCkRnUy9mOVdpTWtqQU5pUVZCd2s4
            bk1qdHltTXdLODhva3BxMWNreS90OUUKLS0tIGhMMUZTcTcrVUExTFhZanp3Nnlm
            SUUwOXVRNllPK25qY0E2R0x0M2w3elUKjvg/ovo48OEsCkw4k+Fteujza97r1YTK
            Kq83/1QhmGCfE0+e56pCJTmBlMG4TO/S3T9cu2qFL5siw195sHF/Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T06:54:54Z"
    mac: ENC[AES256_GCM,data:LEX/u1AfExt5gQTdHZbmbXUQ8fQpKVegQEGYBcPrqRIT2tXumPaTp834/RqQgXaGoYIW4WBlcApz2hruo3tDLgtHpOb1wNaCLXTVtgvSsSEglisBgz9ucy7upVOwzyuLnGpAlGe6wAfx1NnBNrS5KbOAUJXnlYImTtmxQEL6M+k=,iv:VnjK/d769F2KRDTyAyvofvRYCBWhiLfbLXOYhdH9HrU=,tag:L11p/4gbIEiuK/+mywZNrw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
