apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:zfncNfJtSJGMA9KKCVkYrBxFk26gWD7SJ0Wsheg+vp/uGzLcjguw0428D3bQa2hLeQ9iemzKMSldj5KJ5pqgZGPv8ePK6JSGE4eAxMhpT/r9/P37grkL7KpZJ8Cx69BYGx2NwWoyRWpQAKAcLVqOYnpwj5Icy6kZuIbSlFVtiA+VlfEESQE6n2Hk7TcocsWJTDFL+5ahzQ3psasaRvqV/9B4zQr1UbxR04OOF9ixBGUojLfRxxiWSc5pmxTchBN2fJeRaLnFgjQc25nzSfjrXyvxMCfOmfUYQTBmAetjGuvfYcBAyBnyOltUn+aOvgliPsbX2GAhQcZdJ2DGnSxakyi0MFdbnBq2526/EyCb9hO7SY6A0BugFs0CVC0zIkyQ,iv:f7cQUHLIqnJvwewOooqRBIEi9U0GOB9UXHVWhaHdcSU=,tag:35xPuLki8+R2WYXOFcCxHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:N9/1G8Rhe2HqYLns7gP2fEWhVh2d0ls1T4IBUx/rvf9+az1Fxx1+fg1hrLwoKe0u83qpqMWoW0FcYPTT7GqZPnkNjJ4kdaH22bQZc5gt1ccbBgKblYSQAbxA05+gB1cMrZwrcOpMUURKffeHbxQt5UfXhCrfJlV7Eu6M5YJbICzeCtFBWuDSHfk3AbX34cVjbalSKyELpUoqqf2yR0KL6+fOe9K0TCYWovhu+10srUMTwaQsHGC9vela93eUM74QMXFyxPQppa2pVHDG7w==,iv:43Zge9Q+KAOsfROrNga6wfPYiCVZnaYPEDgMXTdH9QM=,tag:KHlgH+IZX6qhilv413Lwow==,type:str]
    known_hosts: ENC[AES256_GCM,data:bzaVmVRJEHmAtRyN1LB4F3rqNpmTG3md8+ABL/G2M0nrmi+VPCbX3PtKs4srone0Bv5BeTpsk8WW5jWiT4IDrihjw11RxrjBjpa8eISqzv0gtGGTjTEz/jNE8GiQHUT+pHFbe0iwzNctbanPP5tDOuZM/C7eJZP2LRbBQL/LKJEbsTPQfrekwKRaV0BMXFk2qATS3Mg/HSu7ZJdIxjKNSfrZwwjuNKxV4rGD,iv:+tYY8JtEU1leDfbfvQOWmb1AlzsaLezvFk+o9Shyl0E=,tag:A4buaUpP2CMxdJI/RkIX+w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaFBodFJDMDJNd2tMNDRM
            MmdjR1FURGtKTHAwNC9NakJmUXNZdGZUelZzCkZFTXVTMXZkREFQVWljeE5jT0VL
            SDVHNXVMa3RDVm9hbi9vT1dYSGE5TU0KLS0tIDhLcWpTaXZMbTRDeFZGR2tQdXg1
            a3ArRWo0WnNrQXFTTGtZMnJ3dHl3WncK+m/h7WZbMCLMVdo/4h9eLFRICcoOyF7P
            ivaG+XsTfHZeXSfjkNM5Gr9MuLXbEFVNQabqlvAouD1f+5S5xMJU+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:39:04Z"
    mac: ENC[AES256_GCM,data:UF1i/SQlEofn2iP2T6uo1vF7bIHkGYm75+mNNHNNbzGZqPv0oZ5c6WmegG6jxfZC7Ge+/Vg5COWiT7qNoO16gQiHlFiB9p5xP8qzrN3PFBh83A/7+CEnfb00W1mD6rWsSJo0XDAYpzkrKX/ODMB6iEfPs+9Csb3YHfqK6gCmkc0=,iv:/YkqZn9VcTos/UcyAz8CxK+ba8sysW2jYSeU8LrCJbs=,tag:52XYl3Yjqa88ZKON6QNCIQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
