apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aeLVHhXiM2K1HDuepYhYMPlqHw+zClpz1od8EKkXDQViIr1Fua3f5WDfkxnaLUIwPLZqfcnMeSwlplGwfZBnjhiP8FFga+Z/Nea0+8ELn4Z0B8B8tf1VUCGBMvZpm3FeVIORKNe9iEzpfLExrbsmlLJocrzed7qkGXpONUg8B0hcPbPD8jtzBbq690y8tp/MvlZxgQ5ZG5qRaPS3c4BuwSPIH3mqyNmgGAJNpykGeTtFi7BOpAOPRHpwND5bHEqeTPLDPP8hEYTbTu05+JGeTnaHS5H/sSVlnG479aRjf9eiTWHY1mMgIpdibMeJPYE6JY8dodb4KMhjJF7x0UOPMYgcoJIeAcB+1aGCogyAgcKVbSTvlJXaQ+/7Q42Cfgpx,iv:ZFr33Ug0RcozcAhHyzouOuItpq7OfbFx+nKhcH2E/i8=,tag:0my+ih/nxpVG0neFslcGRQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:hx1aQPFcvPJD1d/z8ij4Esjpc4ZFDLlEyN5gldSRJlGLgI/rsGW87iYV3plgiOPqaji7wWp0JyZcMAkYZRyvw75x3hLJE63lpsiNtUrIZJmFWywAl4VTOX05yZJmLBFeA7rlBdA7h+OLAgQyAC6DI2HT+P1iv9YR/idjci7bsuNjuHo5S4kWw33U62RBH8mvi8iWR9jXbbWidxvnvNCP2RpCCJf51Vqml3O3qVYmbR0XTaaJ0NeqkE63t/BflTEsINPTti9bMSgLMp41lw==,iv:H0B9jqvJDrV9gjVGYSC3Aswe5ZgSa8ZkBQvLlEQ7SfE=,tag:uLXgW8rbmF6FYSA2WAqUtg==,type:str]
    known_hosts: ENC[AES256_GCM,data:XJowEr6MZ1MuCghAZk7s7XeGxWomzsPMIWqXT184EPy/RnpyolS8LGwAqGhISjd1kwr42Q9DcaUnm8k8qQCB+MgHoQ8DSYY0p0piK3QWXFKeMxNt2a95pHLhIMHIQpUt7ZChKuiLM7bl4dP5zgvV00TNH6xehqtZtql8VkKBzWnrXY5iLA4PmdR4S41KZzYDsSeVjZ10xgYpJrbSsrNKJFK8bESnPOUbImeY,iv:VyJcZypLAICCXVYNR1eLyj/nuxK83jf0QBBDpsuMU64=,tag:n2uJUMcJhQCuwFAQxIKXZQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONVhhbVAwSk0wOEFtRnNM
            TmlDZUpReW9vZU12cTI5eWlwb1A5TkVuSkU4CjZmQXZyVVgzUHJBMXYvOWVWeVV4
            d0tGOWYrc3BtdVE3L2NKbjJmMkpwd0EKLS0tIDN2ekppTmhxZkxFOVpQWTFJaVR2
            SHl2ekRhNHFlQW90ajVlWUxyT3ZDWDgKqhuu93IxZt1x+nE90tGeK5Sw4HIFqaCq
            H5npON5VMuLINwtmtME+6XZmKWKVu4O6AqtGuSVXdEmTlzybDR8Nxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T09:59:35Z"
    mac: ENC[AES256_GCM,data:plK1T6Ez/lGbaaIZMjKgw5MyKiddvR8OtbYr30SCrOUZgv/AfnMgtRBPsfxyB6AXj328w2LOFZVAbmczTKEMO9pLOLGldmcyWuVgK9b6MUZRQd8uauB3nx3uc8OAOz0ZS3+Py79H/22f4ULM7qqOeBQdaJvNuKqayhYK9vYZbtg=,iv:aS79fYQFpVttWw5NWblBjK7U/HtI4T5/91MVvH6qrRc=,tag:2plwtzNlJFzmFWIYK4tsuQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
