apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Y7X4C39xPpP/afj9X4eBymabk/vMC9jvnbjnXXaDIwKOuIQ3tQXsdwL7QksLj37NFbCT0spXOmqOZaUfnHLFzRA6/a9funOulHJzhBHa4s5I+IpI1/DxP1fDfy+hdTQwiPrQ7R0G+e8hHUPB3KVhRnwrjPha2pDUHz9wnScQnYdBZTRuaa8dYyvvPpeT6fL2Uu/T69jrqx8562HBasK1jo+VpFUGkkwLlgZsESq+Ny8sdbzbcvs2/gf7nAzQhp0X9ZLnApyCFroFKO0oyKyDpskhdrbKUni/y5cqVkv5zmvHULDuCQA7K4ejHAXRP+bz9bR/IStzde5p1pKLj1ClkMNag6wFyT0CV5o+vSoqxytZt3BOq3t4WHnvW7TTYwdl,iv:0dMmuYn2NWMpKAy5nv3QaYQoWnTcQACqXJJzglWm4Vs=,tag:g8ReReGJmosq0i/zW2Wh+Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:0VlzEA3DeYV2MWl3UeJhPGxvFgV/mJmGrZPFJu52fRHF7TxNdgds1jPbcycT87EbOG1jNuoXJN2OT6C3/HPf53z9AaoQf1Yq6nTDV9bihhZRA+fmRxSRoUFnuyuTRSETn0ut2UuF65hOj7eRL7FMVir/M2W03C+UG+5Hcf9/Z4QNjXC0JwyFexOTBqS6JDiGc3HakGaOh+eh/gNFCyRcAVqFqizOVFvMTx7koPYGKq0w1dTwbxLhG2RBjIUpFWI5i61Xx5Fn0DAJLUUTzQ==,iv:bkxS0ahoIjNXEY3U7neVFr967q74UdSVQvj/5uNbnuI=,tag:tZKklFpUnw9GfspzD+nbOQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:MKAocdLh2+w7XzEyGcDlH2Htei/FNs88qxpLZQhGFj2svn/smc1hEsAkG8b6PIG/uUf9pI8YVk/ripdcruNuQK6djDTnffEYVyIQoqpb33rBEqOW6b33Vu1eeexFlD50eU0hrFd8eL9qXhr5wumMGT7NCKuothAZ8nWQTdPv5j7ZMSZ0BLbCdW5+nQZRGeGlaUQCHff4W5f0CpXmc5bA+O0kpw+nYhXd4EhP,iv:oHA7GCEI7X5wz5Mao4sxZdHL4Uzd+DS0VdV5qzeFlhs=,tag:plkW3HYcTziKaZIfy+vqgQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSHZTUG9iZm1QUWs5WlFE
            NlpITmkyRzFobmwydkpZTkViSE9uRTR6a3hvCnF2Z0pHN3E3eXNjYXQ4ZEd5V3d6
            R0hBbGJpU0RBUjRaTnBVQ282TExHU1kKLS0tIHpnbUxrM0p6ZC90R3dJSk9IT1VK
            OWFCbGpHUUxEZ0cyMUFmV251TFNUU0EKokpJkw+XyvBFGwsjNLTwikmHoFL41dAG
            J3RN+QfdbBbS+XNupOBVAQJJwpxotZmYDEW/6IwC4EEO+74B177npg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T18:42:10Z"
    mac: ENC[AES256_GCM,data:3hQJOJu04U27AGLml0g4YhhyndoAW2AFYxi1yOOGfv4ezHNxgpssShxAoiEWnD5g5gL0M/S38GCeJMLDn/dmkJI/uL34N97xMmqg2DK8GaXrZH5PAQN4My+jpuc5Nk7Y0NoGfCDDQUUKJhS2kMmn8o/Ua/Lfe3w9o3fSBT22asc=,iv:9VFIEJAib9RvQlix4z95Az5OndBUt8XGyAFqGQwJZqs=,tag:ddGPqw3wgE4k6w8CoOHbvA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
