apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:K/qavyabSu/3XFg9IxAE+Ijq+abwHbGrxcasoKu3tzmGXD0TgTzmQKFfDJ7v5f0Bka8P9nnofD+adofhFc5KztOi3CV/5Qzq+XxXB7SVztX+TImQoeDbIt5AhcmsNiWFpCqSJN0gRFgkUtOHDQwCFa1J89Gb76xR9HNGybM6PhWquKP5guAA8NKF8LxBKdMBCovlWJWjd6HPfpJ+NXyxcB5hR9/vU6TUcraPGKDGkUL6xHLfc86AVv2eRRzR5VqZjbp7Q9OCq7IRV8m/5xSYSCudG2MPg+rVdAykKF5jSTtTK3EwAtNpSCM6ythuaiqAq6uQZctmXYODrd8yqEmYjFIkwd9lX3WwkYxv1m2uNP3yO5Mij+qa7gc48riXyCwy,iv:MvG6oUt2EnW0Jxl9atBSZY444vmxXb2sPSVh7NbzU58=,tag:voFXEVWnMw5nPANcCvWogw==,type:str]
    identity.pub: ENC[AES256_GCM,data:FGX5NsLvDHjXn3dql94NdtDQQkGDtuscE3WyMVijCNlM4CwqZpN+2Up28k7oTQwBPaDSXNHofouiVlioYakLxcFUKJ1ck5SD/wJsHgMSUPt67rUs7tFhorO3FDpP9OkRC3MoMrcygjtle0f4DFh+64+hDGTVLEZ7dkoHsHY8fekhw95PgzWluGJ26M5soYk7vQzGu7Z6LytJGYSa+OQOBBJfU74GfzYoNescVfH922E73K+O0LCmVDK+nmG0Rnv7y3TnekH/aMR/zvEZwg==,iv:C3kIcTEfIgY8nr1zC+rWIRSYnogF4Jl2XY5z2VTWXy4=,tag:SksNGk4IuXINVGLlQr+I0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:yGVk1/A3L6ZUq024YGVRBUW6ybimHjWZcmE8esSl5nn228t/ghCkhOtYbGNS+Mqn9MIDal+twpx3sVDKf7n6/FduuYNDnd45m/PMbc+ZgA0W6TAtrwFBQ51+ycJ0j1rTBTj5BF7x7z4Ta9evsKLasUW/wz5R9D17s4vqdWhHgfKBgD5JpuaalQ6+2GHav71idfpXcp40L+dsjnB+KhNiop51cJ++vw//GjzZ,iv:d/zzIR6XJ9+AbE8THw2wN7dmm1KDxPjuX+37ad5VIsU=,tag:yLfGvYaKpazqr8opfM0lJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRVF6c3F3WWRaYnVucjBv
            WVo4aDdxSEQzUnovOHUzdzE5M2VTa3Y5eFdnCkwzWXZsdUwwRzNCQy9vUHorZnhO
            TU9KYVU2RTFITDFrbmVGMXBzMFppQVEKLS0tIGdDcVgvNGYrdE42NEFMNTN4QnFz
            Q2lDaDV2TTl6ejdBQzJlWUZGUjVQYUkKP3n+gQeHTy2raFuBoLb/N3KLCOAaVhGJ
            E+IRVYwMifG6jtYdplE1qe9T6RKC6VWh1b2zgu/7up24bKryQ8m3VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:28:09Z"
    mac: ENC[AES256_GCM,data:gtpa+/2ugR1uXwRmQL9aC2Zk+cEcX9Sb4IBntf8nwg5hBVvdEYkrcvtqiAxyLodU0h9EtxIC0c16twi4LWEqT8PtoGCqqESj0eBOdr08899BT7B6kbwInPBHSY3Wh+p3JZtvyAJi3SQbyFCrcXgQPlUAJ9/AyF6vYgZ9WrRkLNY=,iv:QLNPtMT8BXqfL65UZuEVQjLP6Smvc8eijjt9DTh6e94=,tag:UIn1Z1TvUdU2J80aQQboWw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
