apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WzxPbLi7LAUYs/IsjxHbHaCxcGLXSazKz+m63oh1FVx/wtmQsMoGx/rfFpJnMTuQGi6g/NTCmuLSpEmTcK04LDrMDunyzCibxiUHjkGjWR2LFDIZXF49p4QqQbtK+XL3RSEOahb9HpS+19h/LXYiVKWC426YcCKNCFV+fjsnU+uVOIO6I+uqVXZNKvmdsFzttrsRAxMar8NlZfEi2B7Es0EAk2D+twNcXJZpTbsOcZ7vYHUR6iYZ8TInlLBvghQNUpwL/c3BuRYbaaqE6gNm5Opylpoi5RsTMAf529c9ab8MTfeXfM0C6PxfqsgGd7Osru5UNCbiQNQYo9LnWrla6vUTggxtIRuuE07+naEgIu6MdHvUMBojuY8JACMxM34y,iv:o9LMS9e0rFbB9guiePLMY3YubdzHjZptFxKufyqQdaU=,tag:+u0pINOBQp+tn8QugHmmsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:vLf9ndjxm219ngK+e+2HsXmMONg/1L2gtnSkNsrxWmizY4z0Z2EBrRsnYpzFHr9R3tAK0M7mveItfUTn+8/VBHGoK88y6jUtXwg6quZEtRiRcpruFuFqO+fQEt8IKg9N4O/MUaLJXOkie4SrtI9GbxERN17B1eNQuAGtTJKTtAOQtFyCStsOOTSE4z02yHldpArzJEzjwbJewc3YULlkh2PWqglmGnP3p0c1/ionKuHFRO6ntMlgBci9Vvh3ZsuCpltoNC8nlMB1CIaBig==,iv:vmiJUftN+TKmNV5T6lB27rzeT6ykGHL1xgyCdJvgDow=,tag:XGpsMBR9G8gOGEAv8q9ywg==,type:str]
    known_hosts: ENC[AES256_GCM,data:1pHLGEn+eYiGl9cpGAtoWqOUK4c5fICBAHVDH32iT+UEED9QWRQy1NFteCkjkNCzVQTX/kmkvYq0UtqiUI5HYnkFH3qbKIldwjOY7BV7EwQ6W59KDk0UpUQGw9BCWQGMomYQTW+UPD7UrUAR4eGiDG+s+Tmd7+C3Q5dopevc3EpEjEa1sw/kRTuHVkghUc6gNhezJFYfJj+BZ1E3Xb74ye38bYReBKKRRsEo,iv:wVVEnrID3OMJxa3ENdaFRpwBsr3aD0SPF7f4Adn0y8Q=,tag:bzRjNVY3fc3AncRzdj9H8Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudVcwWkk1YTZIS2wzTCto
            b3dZeXZJdDdSR3RJOUNkbzhIYVFUOXpOSHdFCk1nZWFZQjhwL0JNUzVmbVIwbE9t
            eDUxL1FBdWErYi8xcEF5eEk2U2RLYmcKLS0tIG0wQTlWYlllSmNNRTk4SFhxYXdX
            NFF3WUdMVTMyUFhqWGJlSkFIOHUrVHMKmnbkUGqlf/yevyh+t+rSN1eUp/aqndow
            yTSvsGy1/sXDZRupK92xX5K8r4dlqcJASq4bFksGTch5tINvuX8I5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T06:52:01Z"
    mac: ENC[AES256_GCM,data:6heJRb85TMyHyDcuY4MzvJQXET60BCqMy053AVHzG+0o5mtshi84LyqTxbCJh87Q7wweBksApqLD1jLzUV1u8pJaxYCVuP4mP0z2RqIAIlUjjbG45zYtzvQkMVXo0Y/pFPnRyyNi7XCnh8FQ9hUI0UW+dupuR/u994o1DT1282E=,iv:lVje8E4wBNH36vzV1Qe6sLYBGrPCtSTyvRmAM+4w7J0=,tag:wLkQHu27hSz7QcaOyWgsgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
