apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WKlTj7690zKO3yXBhXMeRuJ5bOfZ/LXQSbxQt1gC/LCHF6GFLSaaWgokiBng3ddiO7Qf88vFETpCIGaNwmY4sXFmZW+vDwpkGCe7FvUCKr19CIqM8oM3j/xEcado4HE7DXTpYFFARErJ2H12/xyszU5ptLsJw8aE5d9wySwp7NOiDVYLPyjuKnKpPYymBLxg/nM0R/sHmjETPJwHTDSkase0VOglF+9JMcIp8hlVl8IkEWn+PdvbggGp4VrlAlLcAEFi7GsHx7vlTO6JNGPziBkaw71bkDTwwIhnv2AQ/YrpCKraA6Q+fqJ/HtlJnuYsYBO7F2YWdtTwrTu7HP4/EPHeafETkXZC7Ffq3AtKYDwOJN+8q8nrEHMKiZ4Wf01m,iv:7olhpq23GsRLlA2ETSerQOOUkfYgVDrN2EliRkxcyl4=,tag:YnMD+w3jqHoUYYXwzd2j6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:s0lpIgCkKSJ3d4B7G9jOp3D17TMUNprkHqewqlQ/FcliRqUSJAGGM/gfDdMDtMLhFjT2o2UAAK0xRssDx/T0g71HXEhJSpDBLHvIPT98RT2O9UMh8xf/usNlZ5Lc5GDukT0VBVPIwN8kXqX+Zibb8MkuKjDiZUV4bpGn+5Sbwsg/VhkGzCg2Q6JFZYg5aCEBqR0DCBljMU0lGbk+yPaQaed0SX92ZpFEBL3LwfrJLaFxae8k0L75WlfsyUcyZ4xssdFbYV/EG0f8oCBk2w==,iv:ypciawH8/SwtxILnJTDLr6nNKwNX0K0bpq3YFSY5Fso=,tag:2/uSizJnR3fn5ErgU67s5w==,type:str]
    known_hosts: ENC[AES256_GCM,data:KuyvBGSP6uX74hS1AZYPh3ri6k0Wl2EwJLEOJPaOb8Ya7YJiaGXAravc/fpU7ZvhDjvMyhjI36qbHIYSQyOHFiiVdjHhcGPvlynzSYUlFdlY1TLJFiWYes59Pg7GfPXtf1pODQ6KBqEcXp6y0ieD2f/yjf2nJMDMuy8vzHWf+ePliTyu+eZzuoTRvF69Y8yW+iSbq9zpJRvB2F0CbWdYJfu1WCojwMjFtCcN,iv:3Zy56yxJzJ5i0gXh/HqF1OCqiegx1FSh9huAQaCaN7Q=,tag:XQH5bjfSbsH1GSZspf2OlA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TU5uQWVVK1MzNWt1a3RE
            VmZOM2ZmQXdPWXpCbnJzSjE1MXhVekQzRDFjCldFM3psa2RCcnB0anlZTDZsZE0y
            YjdRbEg0WWlmNlRtRm10a1JVOXVKNTQKLS0tIDlxRTBhczMwWXVjMHRYZ0xuSUMy
            THNGWitWRSsyUURkVCs0QWVwalJqSVkKHw4QpHNv3a6hE9OzytWnbUs8EV3jTRRh
            jINm1KUiTUl9L6mkb10ivP3iY/odKxDiZaAcCLweKyvVF1Bj4Gkmtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T20:49:31Z"
    mac: ENC[AES256_GCM,data:M7Dsjqap9N8ciLqG/SWYH1PLfp+sdEs8x+TS2CacMifTwYlBvaI/UQrE/D9ksu2vmmKLwyiGyKDPc2QvPhSwzgArpLlD42ju+bexXF1JIuKmtm5YBzX6QY0ocPRbAqv68rOW81aUKkXxb8KdsVF5jopvMswcqWLo5hd+T39VNwo=,iv:kRZTbMbdCMVTp+pcNlN2CA9aV4UmXDp0ltfIpdGfREI=,tag:WgI6lZ/yYHnkvx5gdHBNmw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
