apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:GYvS1Fnrx4sWNxXbV5V/F1Tr8xl/JCShb/+7+c2F8Q8jlsythwCThHOOusnRyrTjp3LKgTI1rCAJL2pk1poRQuS23L9InAUDOkWVtsXve+JSlEX1TBsDwYJO6ZHIVGUSeZFucEl5cBPo8RhWK8peCJhnA1fm4YqKcbYezlcvWnSLMuEiin1/smBDXTr8O2jvLvFf9yadR1egz4rcf3qgdjXRuGjQqAOL3S8ZAPBwl1v2MV26VtVrhRB5BD0hIDaofoBGasvyAoUp44LnDXg1ox3a8+4XHpQazjc3WkMubbJXaEBduZ2r6lX3LSYO2msKYtOezAdyly1SqgCucCIDDRo11KhQuEFFXmaN9wlF4IlCN74LyEZJPK4ZWJw3Hikm,iv:OuARuqZazB6ovVhJQnrTyl0Pfl+nxgZ/rtcKF6Rs/UI=,tag:tSePvW3jJDQpAN9zsdYUCw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Gcl9yxz2mZ33AKA279hKh7IBLK/0yxo86OkoO546Dy3gsvNrJRGl486km8fkEnhP7phixmTHEkeZXtooMtubxwmgaWO+znjpHuiqUeO/bY2L3kixdBsPjgR5htUZ8vsWoNd8i3kO3CdrfaVPY8Mw0mR6QTX/jLJPwQ2L0WcHoI5xf7tmionWSd+6LeJcb/MGb+jD4zwB52tgNJFCi/+RzLX0HGpDfLABal4yQRbjKxm/u+n0kkFkGi3Fff96DKgTgrbasCLaOoejgzXVQQ==,iv:HsCHfGPyQEDjUpp6MOW2x72P7OWDI/8ecuA9+sO8Pz8=,tag:XZXwYFdweZ0hvZFuH5FC7Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:0mTqxZSBBTUYjzUocSca4Q/uV5uHCvgAKwfY0CPuY6oWF2Roy9TX23oasP1NbVgPy2Mm5oRbcOlyzSnUNBmvNP+S6AoZSemsUHb1Tku1yQhIFQlC1p4WBcbt/k3DO0Bdk1oC54L2rbkkyaMrWkYzjMVDa+hzT5wfbn8J3QtitfWEakWDlVk+X5gZm23jgpcW5eLdFdjCdXfHq8WdMQwnJXIMsbQhzOkL8jTD,iv:s2Py+U5Yb/MOHxlxXjU6yBgyPxrChNqMZrvkJT8s6+E=,tag:c2LFsiz6r1X+z0t5TW0aPA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RC9YTlRhMWNTcnFXa2Za
            UUhjTEtwejRLVXRhU3Q2ck1GWlRhNCtGZ0IwCnlKQkxvWEFJa1l2WWczaDJSaXlv
            akhkNmw2NTBTZzJxZXNPOHdob2hnckUKLS0tIC9sbzdNZ0pzUDRJTHJRNVhQZzBr
            M0FXMldyRXFLZnB6S0ZpckQ2aEY5N1kKA1Dvu9sl8mxd/8Kr0XEeFlxGkw2MUg0K
            0wmr8pM59JPi2PnI9FUW7dmAK4P7jese+pONC8t3fEnYTaEcJAaJKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T13:05:54Z"
    mac: ENC[AES256_GCM,data:Hb/FnalgIsceuX/PmkSfO1ZkZTeqmxPAZ8f80AMykAUFE98twlSWNNWXW2GyGhIz+rX6U+bns/9xn0a62Z3jIEv26omz9WtWP5k3BPNc/hgAtlYVxBCb5khGRtGsNSZKz8Dcvof88rnq7+w8y0KPj0FuIeihY6eHuNw3Epm2cJY=,iv:U2O5+nM+gr3LfHiMzl13HbGx19ij1g5hhpLHlvtfu4E=,tag:VmaxTjH+B7rSdiji7RGANQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
