apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:6Qdq1yrHi5o2c+R+57qZ+qWqOrufHfGTFJ9TUbYp6dikUm3ks9J+m7jcWKxLj/LtV/rm33DJ2/eLO5RMZ/+Uftx4Q/Z/rLtG2k25XXATuzb8ZhEemAfTPtpVIjs5myYL3XEm8V9bixhhkX4dvrEZBHEKis3I9AFNtasBODhzdtyQxE4V6JFUn/5VJ4EXkDacBcrquubqH59454FAxF4gak4aCvi0AGVkH4fQTDhyqpGhXhYyZfnyaTDlS3HOi4d0a6PJQvK5pDOKZLssUt1IGTETbTEoO55aeI+72x7ORff4r4gXBNTsNpF6o8tWvueu/GYb+VTs24s77ivy+NrATorA62N4w3StpF7TsxYTmahWg1rVVThCZDWXLPkmjSo+,iv:PqH4nILpVwGoyFBMmqGgQo21d5Is2JYKs19UIle8cg4=,tag:JK8cdkUJox/SBPBiyutBsw==,type:str]
    identity.pub: ENC[AES256_GCM,data:QXOjeQ6Dsn8d9TtvUN+gSFy8QbbMdegTpDAPjywPmbo0vm7Vaa1vbxdbort2MbQ1MrIzxV54kmWKJkBrgmenTExCwv9G00ATEBXDlIqAuVqB7msp8FlDlAU473LZdyAZYWfOoYx/Wet2OGzyiAxLStqPnEy16suzVl9cbyUuYX3FBkLxdnvxntCXd85pOvu56We4tNQrpULCfhpxciU0TEG8r3dqWgFI4s04qPLRSS3lQqHW9kMC2qOE6wDZcK/BaIharM5m8ndMrki6ew==,iv:l9qAC5faXFvacXvt9Gsg7w1zX6hoOBOA6/INav0ddGM=,tag:gX4v+gfCEQOTwB6847SROA==,type:str]
    known_hosts: ENC[AES256_GCM,data:70KfsH4NpS5kW64J2ToBHVsy9+O7mQKuKPwuVIDNwWUFlFh2g0m78QbMI4//KF8gQliKOfWLGLoMfKAL1AmX9qORD/rt5JTHoNlo1amJTiwTDt60iIHsY6yeBN3ySZeKRuL+N4U1qQF+QzBKIUKbdUKA0E/esTcLcPP5NXVOZAdehpuuu/as9XaFpAnMyI6rdM3eroNYpcsQYOY2Ts4S3RcK1URt3mhf7F3w,iv:lAARRYls9IYmEQui2mH7BDvvsV02o3WUDNGPiNF1PIM=,tag:NCSahIIi9FSQdBptRA28CA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRktwRGwwNUNIaDN2VkMv
            d0RMVjlHdWxWNXJXS0xpUWRRTlNnbEpSVFRzCmNnYVhIYVptMzV2dGpSSmw2VnN6
            Mkk1MXg4NWhIYmY1TUdnYWFFOEc3MUUKLS0tIFRzTWQ2eVkzVDNyRkcrUy80SFky
            STBMM2xJV0w5eWJlVk5yWEFnVllOZmcKkkb+HEELalpF8lDVbFh+53OoZWjCXa3E
            lxK3HFK0KR75itDdyWhS+30em2EDq/VsLJC5OLnnPj171RiFI3DHGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T16:41:47Z"
    mac: ENC[AES256_GCM,data:z1u5JZhdtxfcgSE094KtDw4+IAgbpRNOLOfDGNFP4/PErlkv1wR4+yjyaZCWy25q9llk0iYdCCcBXMPJDesFxJUHbXjhAsNuM5U6ob5H3nzrOoysv3fFBlElJN+PLqK1FBXnDX0tcaplKheeRH2ASATGJlFeeuW6+ZPhMPgh4sE=,iv:0iKCXhjE+8gNvrba/WalNOo6ZDWZPc+rp7hakoYFD7o=,tag:foBkZN+vgkCT/7KODXT9zQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
