apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YNH4Wxyr3Nj0OsF3Wiz8tglhrZ9YxrsYw9/fejXRbUqVG4+zYQu9KaxYZ8IJME+3fga0jeQjGHBv03TCh8p1JWPVcT4ROKmBJUvQBV8L7USR33m3hX4gFwW/GlssUw/hhPgCrfY8znQg1WXe1UsC5UsRZAi/ia8otQFCW36J78NRrSIVZ2WKXoRILNMJhXmTwAxQYSk3YsvQ30+14d+V6pIvFZ6DsIh+ap7W15dupYSKnwuCEaYKiEied8oJO1VZDWkwejyVznENnJCcDoUmtFtSn3Ig7a3bUTRAqpAnd4X+NoywsomPttgNkNjkLaB44qApMGYNJ+jNO1F3hLCFkeNP4eaicZc6jXIlLEMFZnyaBgqr1DgrE9PChRyHPzq7,iv:O0atcucxNPV/iY5Q5GAiWjMMBJXy5FCUI50ofsZrR/o=,tag:IOR/bR5BFEOwzxu7COP/Vw==,type:str]
    identity.pub: ENC[AES256_GCM,data:Z2Yg19tdEaMehHPVfxUudRCzzlRBtzjTn3DmiW3F6TaXz+yLQLva9Lk/rxi81imsML1+WG+7elMAEUqwYNnk334JVBnp2JEv/D+SkZrStClw770ESTR/BU9Ur3BkZDXa3ewPfZ+GNX21dlK01/GVUkw4NxP3Jg4UMbcZbc+dEnJkjkP0hFp8CXJcgkO/tbilXTkvJfS5SjwW+YiEe9SDC3fDhlUPTohXZZssobbBWABt7NDC/hGIsBaAfW4TsrSJoRNy2LTojrkycQCvhQ==,iv:HtMRSGit/L411o3QGhxF+21SlWk0GBJjwDfpugC2QSk=,tag:lAL84DsqUqBzxzBJQ2HUqA==,type:str]
    known_hosts: ENC[AES256_GCM,data:68+NUTMPcqmrILrsZFxwA3fxwwPotM7si5BVWzfknLBOaa55BizoxEIeijfCmsBCDkRO2IYJunt76DviiVtqet45zFT+BiN80P91gXrVGQP4IwOGDZUcf7+Pogqq2PKb2bXbtNYZ/9HfkMU8SEJycyK1+wEuwETNXDu9L5ID3xzsELawMACT6rSdl5V6xXiR3McoFc1OtQOt4or9aov/m94jLGCnRQe2wFvR,iv:HFraA2zye/NJ+1pIwgltlSFzDWA4r5TAADpYciURjxA=,tag:aPH00phS3jMWdHksZuNArQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLazR0eXg3aU1JTHYyL3RB
            cGJON0lJcWxqSWN1Q0xLZnVJcVFFVkVHUjFFCm5wa1RXc0R6Y0kya250MmJHMlBt
            OGN5OE5Gb1hiVW1wME9oRml6YXFZcUkKLS0tIGpQOE11UlovRC9vWi9lNkNjZHpy
            NUh4ME03Q2xYS3FId0NvTTl6MXpGUEkKqumS2+ElQcWupXMoS7QE3U/GWu3H/qUd
            ipTY+d6yLNqW63os0VJspq9ooHaot3bEhzanGyVx7z6eM/guxuofbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:01:53Z"
    mac: ENC[AES256_GCM,data:iLc79XhlOdy7ZNxGSupP98wNB+pZoZE6+olpoUuJTEQA5CpDQtS9CiHPi3KapvBPzFiH7CmrN+Aemu3Uz/hcco8pqUAOuKmyF6ft58v7yc5UG8gq4+ywf+ee50hoHzIK+mmnjDJ+HjuDMDZoREBbCckUSN2b2LV6+pIEwH5IswQ=,iv:qAdQJgRfYG2JGP6awX0Vb+O/N39L6MoL21J0iCmXf5A=,tag:AhBsute0YaPLd1tQQw/Cug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
