apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LA2ojkNXVOkB1wrTyhflYmekoEj/5NZ8A3uda0EF9lnyx+UbYB0NecPLPqhFQ0YaUwh4yxg7UYytZuyY/tnu3i47BcWU69Y1VGyf3N/WT5p86Yq031/qPGCiRht3/no0CtvaCg32DJcCcUL++Y6adi9MniPSYmtjsrh+i2fqWAEMrqmSjQecOJvBe12fd9HJh1BH0yXySGpx/1F8gGTgdRSc8P73uKBz7fK9bEvPyskyECMaTlfiGnqHXI7ugBjTF1P0mLj39MATFhtLi07fjbEt/w7IyiBhtkXO9xCS7aH7FrrREm+LqHxj481mOvhkXf73Do/bUAhC8+UTls9i2Oo9hnRMHjQK+n29LZZPtfOT3hR+ca1Vu5ItnZi++xBr,iv:4vecxXc6bu2/xgdM5owxXD/TpzsSwKXkq9oBzVcQq+E=,tag:6GNNMDJZ5SNakEqXCZiI9A==,type:str]
    identity.pub: ENC[AES256_GCM,data:AqsxvlRlDONOAdeji2klTccC7zMeswZnCBu9wkQwzHpGzdWhKQQUj2BJPAZDyBWNkfCobf7XX51BI07/pzXqkF2TgGjrVo1e7u4l9vk7XUfQ9ghJ5OIdkTsWPWY+oTfZ8KxAMHco1T4EDtJkRcoWXz++jeapWiAXmaf58O/Yn5D1BA6gV1n7fmnKL9NAZb340utzEE/6jxrGqqDfBbIztPQIPql2UyRczXqcjhsP0LHNx1DvR5Vhd+IU/9QdNUBr8AvT7IKPms6F+NCOOA==,iv:CUlP+EU8U+5D0zw30QUWjS6JpvaFVHZyUG9+5fzVHYE=,tag:2n7EntorVz07BMSNXmYtOA==,type:str]
    known_hosts: ENC[AES256_GCM,data:spJXuoG+pDSIRm3bFlyM8RJJljPA+aMC5YNTJATIKkJRWo9fZkp6ySds9yCYNL5cjTqYGmCPr3KWs2q/tai/gcxCLYFtplVveZo+GcFuBxEICNLbCPnHmAr1KCmhZlWNRUnCmB35pM5XnjcuvJ/UTMweaH1jkmE000s0UXolQyOx+QyrfrzJvrC3zN5qC6KCjzZS06ANOkK0+zbA7X/iu0PS2bg+qbEc10Zv,iv:/ZAUAs6A6cppKBRTNcSk9SVG5VgboztDdJCq7c6WHRg=,tag:jXA5NpopvhpFzuN5nHNWAQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SVNGMjZncm9DcXhlL1BN
            TUxPUWNMRjBFa1pnTE1CRE9UdWdYU0FMT1RFCkVaN1A3NmVVc3ZKNmpmUWN5cENI
            VktVQ1gxdUVHVFpFQWhSN2tJYXlTV0UKLS0tIGRHZ0c0NGxYclFIR3UwR3VxbXFF
            MWd2UW5NZTRlRnZsSFQwTGlwUWRuR00KL7EppaGoe2rPvlFV7uNgT49HfSmL1oxl
            3UhwFIqjxZT/ozPtuVtTOL2FQtWbeZCPNoZotNtmMeVcASiJXEjLDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T23:15:23Z"
    mac: ENC[AES256_GCM,data:BAwfe7mYpPQrM1cW8Kh2dHlfyMiK1fTxx7zIPUaqczg4hpViBzkrHIjyuaWTS+TaGFqlJcz37PjieAy3RtIBwf/ZfQPrt/AD9qrWqen/Ki1x5FQIH4LQCcTo7xfOCChANsbrL2XLhGAckXlpaCtmWwGg22vCOcYQqTByhbWd6eg=,iv:lFX2/8fVZ7z+QH6E+BJnzFybTkLuBzS5vh79enjsBw0=,tag:tPy5v9QxlKx4CepB58o5iQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
