apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/RAZBwleo0PFRIKfQp8vbx7FY20e7mBEvEs043K2DERiEJQWFHOtCOX9XHqb5r+waEp8LP58cMAD3vXvLpCQKgQ2+EZ3hK3uVnVTiOISMLIY5JqFv2qGtH4NaRwLAXkBlhO6K0Z8R84kcRsgaFZ/1MsxU9ofuWMco06+9L+kxoeI/tvMPveCQO38U225yUs8+FqWDkU7VIR/BEWYfrMhEwoOTG48/LyRnK3xZ0kknQJllKgErN6cng5uATVISc8Mun58ASczyHB96aovxEu1ZE7QllbKfg3UV3E9oX78UYQg2++tozeTNVKaDKN1oHILwE0Z1HP1Vkuxv4exjeQApB1CfQeQQ8ehmgAjyOpD+VDAt/T+YowzoAvFgHKobXJ5,iv:CWcujLNfrVXwjaLVy0oHC6L3JzM51rjFFE4kAlq7sxI=,tag:3zu+tHq2lZsNdC7PX1LCmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:MNJNXlk7q3RD5y0XrB0iIcVfaWHevMfk5oFL9py8dmdEQJTQCuB1we3+L5M8DdpW1MfjG72X6jPxCftpJtp9TrWezzrzu0/kS3qWq1iuZaBMrsBrJh8t4+6dh3ZSWYKsiC4S5byVUVILmpWhGAzMzru1c6FvJdvdFzQdLbSEvIIqNuV0Gdwau/AzOR+68UAtox3QH2Txkqc/bBaeMTmHL97A/EJtdV+gNB3GgiLeLC0E/wBAi52xmbDAMuWgRGAapmTUW9/WLhHKa2BkdQ==,iv:53eWvtmcwXqHxR5Mbk2iHAD/xMl23V11JSRjZ1rSoL8=,tag:zZNNyLzIdN5jyOoyGNqhDw==,type:str]
    known_hosts: ENC[AES256_GCM,data:R67cJLe+5Dbqg3jJwBgKhCAvuM1qCfAffhuV5gVqrtJYK+PAxgWVNhv2AVAlJkuLqh72p1Bk5RaldnnvKtmKM/FayNES0gpqGiOgBrnmvA3KFmz5GmGV6IC0qF17a1Y42LoMRa5PKRONB0RadvDI4uy1Ac65pQyb5znvfPTVD+BjFb9tXDdRZ8b5JnU7AUAOE3x0IEFrm1PxtakahQ29F/I71T2mdNFNDIQB,iv:D7O366sA/hU0C7d5ZxpKDaJ4PsvokLhrAb1czPG2YXQ=,tag:oEzfPybLcKUQu3Ot7JeJww==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNENvR0QxUWJ5Y29TeUdt
            cUhvU2lUZXNCaW5pSWlCVThibGo4YnBsM2djCldiOWljZktyeWxwUFJDR1RUNGFv
            VUp2anpqd2QvTVgyZllhdnNJUVBXVncKLS0tIFV6SFdZRjlRMC82cVEyVXB5OHBo
            cHB6UXIzOXQwUnVCOElaVGp4TkJkZmcKe61l3Juz1U+xuE5Tk2/wjgrCkttqlJZj
            knbD1PWE+KeIIu6VRnaLCCflV6JRnpfWH++fSmXrahQvPF763Q0mTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T09:44:29Z"
    mac: ENC[AES256_GCM,data:6uKatJdDEmjZN6wzIbCoNVuk9eLWEOdH7uJx4B/SshAcl/at4HnEKlYdR5TxcRQOiFZpmBW/+30sa9EylWoEKntYgqeroRFwIo79jFIlYGkJBCXum7a0N6w/1AJJFsDciwmitRP/HEruDdOwCoANtkCpm5JC7C4Pt6C5dXh5+A8=,iv:U7Flnn1Xvxho/YBuAYJXIJHGEMg/ghzwfgBxAWmHjRw=,tag:mwA6xJ3MjGLh19D0r7OoTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
