apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tkbaXNZYykuajFPwIP7wJIa1XGGEwsFPv0JvhJ3WexIO6IWJkA1L0Hz1unUBdRFPoMQQ8nQ6FkIDwhGGVX09Zv6z3SS2u4ifP1uLZilnanVefG/c4PIFG9Tn7+JOK2NhbpzUUSg59MDOAAsUkcyoiqN3WZB2yWmtl11gab992iKjeK5M+W7AyNwkQA0FF0L/Rc4/avGOXoY7LmlGm8tJgmArllz0HuLTFTqTsFrl4Dvb4yyecNn9eAIBOR85lwuTviPOA+RJvCLf7WBFBIi0164k49JwzQ0w8OynY5iqnwDQQsxSBCMmVEnqFWadQGStT2PbC91DJ2o5QaWDnhkrfxyVbryojFOWP7V+L4SXiOcmguQ0jnxfYal0vdxxHmO4,iv:UNzMIgcqS8FlDUGAi+JOEl/B2xf3129pDGQ/Yc3ANq0=,tag:fDYJkLYlCQcaRrg3nM7Dng==,type:str]
    identity.pub: ENC[AES256_GCM,data:V4WKZLMJoy4rZksfkeZIy5zxFgu/TpuKH/npcGzQan2h/5dIyjtr6CEyeR9THwClelKu3MKFEWVnZRdIuqtsMUIEPzoCP/aDG1fQpGZpZlYVMG0a+D5sUKDY3X9Bf1v7oILN/WczHdwTRmvo4EdXn9FuiZ24udrE7t8bMJLDc4vQeXJIisDvHHuJkl6kkIeYUnnlXyDQQVtbE44LXh4F3EKs3ZxqnDOiY74r8/vxHbmTt9e5UHzvk1nhPlwuqWZbLyuWK5Fc4WYl/iVe9Q==,iv:nrbnw5xtnYNK9CLvy4iX10j3mYAivXqozDRTK+UzdJw=,tag:nXp01ZUktPQyPZiFXRuq9Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:eNMEuyeFqoM9NU4nhdSG6agTVi46hFS8yk+blYXydKqjMgUIOwKbq31t7PQyoyVK954QMmgiiS205/XaMq6M3eV/Qfvy47tep/SAJ30xyRWUd/JZFIjf/oylXMiCHAR0omCZ3w6ExWUeXA5vFqAYUL69FboWf894KoomGhVh2/risf0+8mrdO4F6mFPsAa20shrT/dsiuCaYENqF7l3WIhEU2yUipRyMKTPz,iv:uP/eiokrMKIgByu1B0TiUi4bGiF62uCtUL4vx8apqBw=,tag:S7wXx7cuCTFEbCu9kUSBHQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaWdIRytxWEJ3T0xHRXRh
            VkRlTEs3WEx5eGdnTFNlVGN4OVA1TlRxWlRVCjFVZHFudUkyZGhabFA2OEF4WHVN
            M3lCbFplZDkvRCtEVlZSK2VFbFlQK1EKLS0tIG1NRDJaZ2lWa2NNaHVld2NBNUhD
            d1V3V05tZWVpVHBLbDlUOHBBUE9rRFEKUbUpdcOMvknByPuFcqRufWt49um3mJoB
            PUBeR0osdLGeBLgqA1otilQuK60UPz5Ec6jfM6aq7i8H7CbBO+vlCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T19:52:04Z"
    mac: ENC[AES256_GCM,data:rHcJWbgTobfNOutHQ4lO+cO98KLBLFMGImuDiAekTVR6kWCAgxgLqRubT1XieRoL51e1nUW+9sb8TEGuQIw27yjlLo9kXmpAIY3e77kwYaBTwvEYI1SWPxdIKLFnUnf43A46slO4NpQMhqelW8dq3TFIMkk76EuhIrNJqy+cM9Q=,iv:tnF09yITitDNdGXLqRv9ej41I1DjZwPUKaIG12y8DAU=,tag:on/izbYHxawaMPAZsNwa7Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
