apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IkfzUi8oPw1vToJ3ZvIvUHZJxkKQ3HhbIWu4wO/4MWfZjwaMhRRJ3vvjf38T/NBQZ32UNXwPzln3LFIa+eOIT/FGdopKqPALohiQ+VgEuNfisXCU9xurP+UdvhMufR8w+nWJ0Ak4r7LumjOnGQpPVjFGxFJLMuUPFv2e/6x9NnDYG8G5TuNNgFzvDXZ4yma27cNC5eCkMW8KIXU/uYZsRjPn8F7xXio2ebQ/A2F344tIxCGFdTeos3sfwQTDJnQne6AC+SphxxpCvGkEvNkFwo+s/npDEvpxtRkSoD1/1siEFWOtHoi6ejphG/nZ8kEMIjPBzOMm9yWBnw+MoVsJz6q/zRKr70JRSy5TmZ8+4OLouu8SUXEV8xUYSQoqiYZG,iv:W00VdGbmVaas1mdrXSVVfBexdj5BNFlDKT5iPbsTIcY=,tag:6LoguwK+k8DSLhS6ZRACIg==,type:str]
    identity.pub: ENC[AES256_GCM,data:GFHndsxhlow/tEPlWPkEeRxyYvI55z0Ur96+3GiwetlYXJCJGlWK8kQ/AY1CqQITsgNAE/h5C6HETtKh+Lb/gHKHPjSYbJM7qBSvuLke9yxo7e+fXrJYnIu9A2dJK0B3MXRYUv1qnHKTvGKveaWXPfzaLMgWz0xl9GYuRcxuub8YN1Xint+M+qRWHPdqYYZ0Nkl92hQlMTjjs/YwYDjooHIxJCpEFDYWtEKIRVCtA14GE8bzFKLWiFMk5Eib4/kDZwy/BzP1/dHHd2vV9w==,iv:SaYIUpcqrSqn7rE7XWXUXr7ec0BcHm/croMPn6u1FwE=,tag:DVX55sVX2wcuSRsVNOCjxg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8gqbhKRqawn/xFmD6wFbUfUjgyyh9FtsXgBSnDoLe4PI5noFe7eEGR/9bFXlVuZ/h0/pZ9S0KjfZyWq15h3aVYWf7Nb0O2CIYJHijrDMdRfFh3wzUcNB+2XnQPNxVR7bQJo3PiqYSSRspoupp2FsOoUW5XX1jvDpfCkwMd/0x2F5jnsuMcbpPqvg8kng1A1AUrHq0+GTQXvShI7/3skOyS2j84YCi9GtDUFg,iv:3uqcl3F13bnIo+ThvMByK+JCiQ/7OEgFjzZlFDgXYM4=,tag:G9vc3gKeTHre73OXsvTMCw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1cn79agmdffpagt5de9zg6l4zj64z7evgu86yq8u84r90rndnvpzsnesh46
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSXVHWnhraSsvb01Ua2JP
            MFN3VjM0dEpNSjBiSFFycDBZU3lwYUxyWWtNCnhVRTBFOU1pb1RYaU9jQ09mTHZ1
            V0FKbms3amw4cVhDWk1LUmIxdm9jSE0KLS0tIEN5eElwU2JBWUhjZ0dRM2pLQXgz
            RGNPYzhWK1UzdkZUVTQ1SE9kWXB3L3MKCgaNSBWShY12sj0KEdKSfP/SWWnmWJES
            jpGdwMitb9Bd6QkPfQuvQ6GgO1RjpEO036C00h4jUtPkd0a5PphXIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T22:54:53Z"
    mac: ENC[AES256_GCM,data:ZsQ1lSSF30JgbEimTIHZdu8iSbA2zRtMiEghW7P2RdCXhqCiIzhiU6XZ8m752b62zAC6WxwgCO20om6fetne04WdGJhnY9JpoZz9XqoT7EWiJcf+U9fphi4U8XuJLE4uMEYG2CpooLekCKXLniK1+IEV0nBgZ4Qd2/ElyBYIpC0=,iv:xEiC8F5ncAvgpqO/yP8PTl3r9k0GlMXQ1mdeQFxumP4=,tag:/Xk32QL4ZQV0xCBwkvwjNw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
