apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxy-scrutiny
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/external-apps/proxy-scrutiny/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

