apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - namespace.yaml
  - nfs-media-pvc.yaml
  - plex/ks.yaml
  - prowlarr/ks.yaml
  - qbittorrent/ks.yaml
  - radarr/ks.yaml
  - sonarr/ks.yaml
  - stash/ks.yaml
  - xbvr/ks.yaml
  - komga/ks.yaml
  - profilarr/ks.yaml
  - flood/ks.yaml
  - bazarr/ks.yaml
  - shoko/ks.yaml
  - jellyfin/ks.yaml
